// Auto-generated by data-generation/project2/generate_fallback.py
// Do not edit manually — regenerate with: python generate_fallback.py

export const FALLBACK_ORG_MODEL = {
  "company": "Meridian Technologies",
  "model_version": "1.0",
  "model_disclaimer": "Model coefficients are illustrative. In production, these would be calibrated from your organization's historical data. Methodology references cited in documentation.",
  "divisions": {
    "sales": {
      "label": "Sales",
      "kpis": [
        {
          "id": "pipeline_value",
          "label": "Pipeline Value ($M)",
          "baseline": 45.0,
          "unit": "millions_usd"
        },
        {
          "id": "win_rate",
          "label": "Win Rate (%)",
          "baseline": 28.0,
          "unit": "percent"
        },
        {
          "id": "avg_deal_size",
          "label": "Avg Deal Size ($K)",
          "baseline": 185.0,
          "unit": "thousands_usd"
        },
        {
          "id": "sales_cycle_days",
          "label": "Sales Cycle (days)",
          "baseline": 92,
          "unit": "days"
        }
      ]
    },
    "marketing": {
      "label": "Marketing",
      "kpis": [
        {
          "id": "marketing_spend",
          "label": "Marketing Spend ($M)",
          "baseline": 8.5,
          "unit": "millions_usd"
        },
        {
          "id": "mqls_per_month",
          "label": "MQLs/Month",
          "baseline": 1200,
          "unit": "count"
        },
        {
          "id": "cac",
          "label": "Customer Acquisition Cost ($)",
          "baseline": 8500,
          "unit": "usd"
        },
        {
          "id": "brand_awareness",
          "label": "Brand Awareness Index",
          "baseline": 62.0,
          "unit": "index_0_100"
        }
      ]
    },
    "engineering": {
      "label": "Engineering & Product",
      "kpis": [
        {
          "id": "eng_headcount",
          "label": "Engineering Headcount",
          "baseline": 85,
          "unit": "count"
        },
        {
          "id": "feature_velocity",
          "label": "Features Shipped/Quarter",
          "baseline": 12,
          "unit": "count"
        },
        {
          "id": "platform_uptime",
          "label": "Platform Uptime (%)",
          "baseline": 99.7,
          "unit": "percent"
        },
        {
          "id": "product_nps",
          "label": "Product NPS",
          "baseline": 42,
          "unit": "score"
        }
      ]
    },
    "operations": {
      "label": "Operations",
      "kpis": [
        {
          "id": "ops_budget",
          "label": "Operations Budget ($M)",
          "baseline": 12.0,
          "unit": "millions_usd"
        },
        {
          "id": "fulfillment_rate",
          "label": "Fulfillment Rate (%)",
          "baseline": 96.5,
          "unit": "percent"
        },
        {
          "id": "csat",
          "label": "Customer Satisfaction",
          "baseline": 4.2,
          "unit": "score_1_5"
        },
        {
          "id": "churn_rate",
          "label": "Monthly Churn Rate (%)",
          "baseline": 1.8,
          "unit": "percent"
        }
      ]
    },
    "finance": {
      "label": "Finance",
      "kpis": [
        {
          "id": "dso",
          "label": "DSO (days)",
          "baseline": 48,
          "unit": "days"
        },
        {
          "id": "operating_margin",
          "label": "Operating Margin (%)",
          "baseline": 18.5,
          "unit": "percent"
        },
        {
          "id": "free_cash_flow",
          "label": "Free Cash Flow ($M)",
          "baseline": 12.0,
          "unit": "millions_usd"
        }
      ]
    }
  },
  "interdependencies": [
    {
      "from_kpi": "marketing_spend",
      "to_kpi": "mqls_per_month",
      "coefficient": 0.65,
      "sigma": 0.12,
      "lag_months": 1,
      "relationship": "proportional",
      "source": "HubSpot State of Inbound Marketing Report",
      "notes": "Diminishing returns at high spend levels; 15% spend change -> ~10% MQL change"
    },
    {
      "from_kpi": "mqls_per_month",
      "to_kpi": "pipeline_value",
      "coefficient": 0.55,
      "sigma": 0.1,
      "lag_months": 2,
      "relationship": "proportional",
      "source": "Forrester B2B Marketing Benchmark Study",
      "notes": "MQL-to-SQL conversion ~13%, SQL-to-pipeline ~40-50%"
    },
    {
      "from_kpi": "pipeline_value",
      "to_kpi": "win_rate",
      "coefficient": -0.15,
      "sigma": 0.05,
      "lag_months": 1,
      "relationship": "inverse",
      "source": "CSO Insights Sales Performance Study",
      "notes": "Larger pipeline slightly dilutes win rate (more early-stage deals)"
    },
    {
      "from_kpi": "marketing_spend",
      "to_kpi": "brand_awareness",
      "coefficient": 0.4,
      "sigma": 0.08,
      "lag_months": 3,
      "relationship": "proportional",
      "source": "Nielsen Brand Resonance Framework",
      "notes": "Brand awareness moves slowly; takes 1+ quarters to shift"
    },
    {
      "from_kpi": "marketing_spend",
      "to_kpi": "cac",
      "coefficient": -0.3,
      "sigma": 0.07,
      "lag_months": 2,
      "relationship": "inverse",
      "source": "ProfitWell SaaS Benchmarks",
      "notes": "More spend improves efficiency (volume discounts, brand lift)"
    },
    {
      "from_kpi": "eng_headcount",
      "to_kpi": "feature_velocity",
      "coefficient": 0.3,
      "sigma": 0.1,
      "lag_months": 3,
      "relationship": "proportional",
      "source": "Brooks's Law (The Mythical Man-Month); Accelerate (Forsgren et al.)",
      "notes": "Sub-linear: hiring 10% more engineers yields ~3% more features after ramp-up"
    },
    {
      "from_kpi": "feature_velocity",
      "to_kpi": "product_nps",
      "coefficient": 0.4,
      "sigma": 0.08,
      "lag_months": 2,
      "relationship": "proportional",
      "source": "Pragmatic Institute Product Management Benchmarks",
      "notes": "More features (when relevant) improve product satisfaction"
    },
    {
      "from_kpi": "product_nps",
      "to_kpi": "win_rate",
      "coefficient": 0.25,
      "sigma": 0.06,
      "lag_months": 1,
      "relationship": "proportional",
      "source": "Bain & Company NPS-to-Growth Correlation Studies",
      "notes": "Higher NPS drives referrals and competitive positioning"
    },
    {
      "from_kpi": "feature_velocity",
      "to_kpi": "platform_uptime",
      "coefficient": -0.1,
      "sigma": 0.03,
      "lag_months": 1,
      "relationship": "inverse",
      "source": "Accelerate (Forsgren, Humble, Kim)",
      "notes": "Faster shipping can temporarily reduce stability unless balanced with quality"
    },
    {
      "from_kpi": "ops_budget",
      "to_kpi": "fulfillment_rate",
      "coefficient": 0.7,
      "sigma": 0.12,
      "lag_months": 1,
      "relationship": "proportional_with_floor",
      "floor": 85.0,
      "source": "Operations management queuing theory; capacity utilization curves",
      "notes": "Budget cuts below threshold cause exponential fulfillment degradation"
    },
    {
      "from_kpi": "fulfillment_rate",
      "to_kpi": "csat",
      "coefficient": 0.8,
      "sigma": 0.1,
      "lag_months": 1,
      "relationship": "proportional",
      "source": "ACSI Methodology (American Customer Satisfaction Index)",
      "notes": "Fulfillment is the #1 driver of B2B customer satisfaction"
    },
    {
      "from_kpi": "csat",
      "to_kpi": "churn_rate",
      "coefficient": -0.5,
      "sigma": 0.08,
      "lag_months": 2,
      "relationship": "inverse",
      "source": "Reichheld loyalty/churn research (Harvard Business Review)",
      "notes": "Satisfaction decrease drives churn increase with 2-month lag"
    },
    {
      "from_kpi": "churn_rate",
      "to_kpi": "pipeline_value",
      "coefficient": -0.35,
      "sigma": 0.06,
      "lag_months": 3,
      "relationship": "inverse",
      "source": "SaaS metrics: churn reduces expansion revenue and referrals",
      "notes": "Higher churn reduces upsell pipeline and word-of-mouth leads"
    },
    {
      "from_kpi": "dso",
      "to_kpi": "free_cash_flow",
      "coefficient": -0.28,
      "sigma": 0.05,
      "lag_months": 1,
      "relationship": "inverse",
      "source": "Derived: $200M revenue / 365 = ~$548K per DSO day",
      "notes": "Each day of DSO reduction frees ~$548K in working capital"
    },
    {
      "from_kpi": "free_cash_flow",
      "to_kpi": "eng_headcount",
      "coefficient": 0.25,
      "sigma": 0.08,
      "lag_months": 2,
      "relationship": "proportional",
      "source": "Corporate treasury reinvestment allocation norms",
      "notes": "~60% of FCF improvement allocated to reinvestment; engineering gets ~40% of that"
    },
    {
      "from_kpi": "free_cash_flow",
      "to_kpi": "marketing_spend",
      "coefficient": 0.2,
      "sigma": 0.06,
      "lag_months": 2,
      "relationship": "proportional",
      "source": "Corporate treasury reinvestment allocation norms",
      "notes": "~60% of FCF improvement to reinvestment; marketing gets ~30% of that"
    }
  ],
  "sankey": {
    "nodes": [
      {
        "id": "brand_awareness"
      },
      {
        "id": "cac"
      },
      {
        "id": "churn_rate"
      },
      {
        "id": "csat"
      },
      {
        "id": "dso"
      },
      {
        "id": "eng_headcount"
      },
      {
        "id": "feature_velocity"
      },
      {
        "id": "free_cash_flow"
      },
      {
        "id": "fulfillment_rate"
      },
      {
        "id": "marketing_spend"
      },
      {
        "id": "mqls_per_month"
      },
      {
        "id": "ops_budget"
      },
      {
        "id": "pipeline_value"
      },
      {
        "id": "platform_uptime"
      },
      {
        "id": "product_nps"
      },
      {
        "id": "win_rate"
      }
    ],
    "links": [
      {
        "source": "marketing_spend",
        "target": "mqls_per_month",
        "value": 0.65
      },
      {
        "source": "mqls_per_month",
        "target": "pipeline_value",
        "value": 0.55
      },
      {
        "source": "pipeline_value",
        "target": "win_rate",
        "value": 0.15
      },
      {
        "source": "marketing_spend",
        "target": "brand_awareness",
        "value": 0.4
      },
      {
        "source": "marketing_spend",
        "target": "cac",
        "value": 0.3
      },
      {
        "source": "eng_headcount",
        "target": "feature_velocity",
        "value": 0.3
      },
      {
        "source": "feature_velocity",
        "target": "product_nps",
        "value": 0.4
      },
      {
        "source": "product_nps",
        "target": "win_rate",
        "value": 0.25
      },
      {
        "source": "feature_velocity",
        "target": "platform_uptime",
        "value": 0.1
      },
      {
        "source": "ops_budget",
        "target": "fulfillment_rate",
        "value": 0.7
      },
      {
        "source": "fulfillment_rate",
        "target": "csat",
        "value": 0.8
      },
      {
        "source": "csat",
        "target": "churn_rate",
        "value": 0.5
      },
      {
        "source": "churn_rate",
        "target": "pipeline_value",
        "value": 0.35
      },
      {
        "source": "dso",
        "target": "free_cash_flow",
        "value": 0.28
      },
      {
        "source": "free_cash_flow",
        "target": "eng_headcount",
        "value": 0.25
      },
      {
        "source": "free_cash_flow",
        "target": "marketing_spend",
        "value": 0.2
      }
    ]
  }
}

export const FALLBACK_SCENARIOS = {
  "scenarios": [
    {
      "id": "reduce_marketing_15",
      "label": "Reduce Marketing Spend by 15%",
      "description": "What happens when we cut the marketing budget by 15%?",
      "input_changes": [
        {
          "kpi": "marketing_spend",
          "change_pct": -15
        }
      ],
      "cascade": [
        {
          "kpi": "marketing_spend",
          "baseline": 8.5,
          "change_pct": -15.0,
          "projected": 7.22,
          "lag_months": 0,
          "sigma": 0
        },
        {
          "kpi": "mqls_per_month",
          "baseline": 1200,
          "change_pct": -9.75,
          "projected": 1083.0,
          "lag_months": 1,
          "sigma": 0.12
        },
        {
          "kpi": "brand_awareness",
          "baseline": 62.0,
          "change_pct": -6.0,
          "projected": 58.28,
          "lag_months": 3,
          "sigma": 0.08
        },
        {
          "kpi": "cac",
          "baseline": 8500,
          "change_pct": 4.5,
          "projected": 8882.5,
          "lag_months": 2,
          "sigma": 0.07
        },
        {
          "kpi": "pipeline_value",
          "baseline": 45.0,
          "change_pct": -5.36,
          "projected": 42.59,
          "lag_months": 3,
          "sigma": 0.1
        },
        {
          "kpi": "win_rate",
          "baseline": 28.0,
          "change_pct": 0.8,
          "projected": 28.23,
          "lag_months": 4,
          "sigma": 0.05
        }
      ],
      "quarterly": {
        "q1": [
          {
            "kpi": "marketing_spend",
            "change_pct": -15.0,
            "projected": 7.22
          },
          {
            "kpi": "mqls_per_month",
            "change_pct": -9.75,
            "projected": 1083.0
          },
          {
            "kpi": "brand_awareness",
            "change_pct": -6.0,
            "projected": 58.28
          },
          {
            "kpi": "cac",
            "change_pct": 4.5,
            "projected": 8882.5
          },
          {
            "kpi": "pipeline_value",
            "change_pct": -5.36,
            "projected": 42.59
          }
        ],
        "q2": [
          {
            "kpi": "marketing_spend",
            "change_pct": -15.0,
            "projected": 7.22
          },
          {
            "kpi": "mqls_per_month",
            "change_pct": -9.75,
            "projected": 1083.0
          },
          {
            "kpi": "brand_awareness",
            "change_pct": -6.0,
            "projected": 58.28
          },
          {
            "kpi": "cac",
            "change_pct": 4.5,
            "projected": 8882.5
          },
          {
            "kpi": "pipeline_value",
            "change_pct": -5.36,
            "projected": 42.59
          },
          {
            "kpi": "win_rate",
            "change_pct": 0.8,
            "projected": 28.23
          }
        ],
        "q4": [
          {
            "kpi": "marketing_spend",
            "change_pct": -15.0,
            "projected": 7.22
          },
          {
            "kpi": "mqls_per_month",
            "change_pct": -9.75,
            "projected": 1083.0
          },
          {
            "kpi": "brand_awareness",
            "change_pct": -6.0,
            "projected": 58.28
          },
          {
            "kpi": "cac",
            "change_pct": 4.5,
            "projected": 8882.5
          },
          {
            "kpi": "pipeline_value",
            "change_pct": -5.36,
            "projected": 42.59
          },
          {
            "kpi": "win_rate",
            "change_pct": 0.8,
            "projected": 28.23
          }
        ]
      },
      "narrative": "Cutting marketing spend by 15% reduces qualified lead flow by approximately 10% within one quarter, contracting the sales pipeline by an estimated $4.4M. While this saves $1.3M in direct marketing costs, the downstream revenue impact is projected to exceed the savings within two quarters. Brand awareness erodes gradually over 3+ months, compounding the pipeline effect."
    },
    {
      "id": "delay_engineering_hiring",
      "label": "Delay Engineering Hiring by One Quarter",
      "description": "What happens when we freeze engineering hiring for a quarter?",
      "input_changes": [
        {
          "kpi": "eng_headcount",
          "change_pct": -12
        }
      ],
      "cascade": [
        {
          "kpi": "eng_headcount",
          "baseline": 85,
          "change_pct": -12.0,
          "projected": 74.8,
          "lag_months": 0,
          "sigma": 0
        },
        {
          "kpi": "feature_velocity",
          "baseline": 12,
          "change_pct": -3.6,
          "projected": 11.57,
          "lag_months": 3,
          "sigma": 0.1
        },
        {
          "kpi": "product_nps",
          "baseline": 42,
          "change_pct": -1.44,
          "projected": 41.4,
          "lag_months": 5,
          "sigma": 0.08
        },
        {
          "kpi": "platform_uptime",
          "baseline": 99.7,
          "change_pct": 0.36,
          "projected": 100.06,
          "lag_months": 4,
          "sigma": 0.03
        },
        {
          "kpi": "win_rate",
          "baseline": 28.0,
          "change_pct": -0.36,
          "projected": 27.9,
          "lag_months": 6,
          "sigma": 0.06
        }
      ],
      "quarterly": {
        "q1": [
          {
            "kpi": "eng_headcount",
            "change_pct": -12.0,
            "projected": 74.8
          },
          {
            "kpi": "feature_velocity",
            "change_pct": -3.6,
            "projected": 11.57
          }
        ],
        "q2": [
          {
            "kpi": "eng_headcount",
            "change_pct": -12.0,
            "projected": 74.8
          },
          {
            "kpi": "feature_velocity",
            "change_pct": -3.6,
            "projected": 11.57
          },
          {
            "kpi": "product_nps",
            "change_pct": -1.44,
            "projected": 41.4
          },
          {
            "kpi": "platform_uptime",
            "change_pct": 0.36,
            "projected": 100.06
          },
          {
            "kpi": "win_rate",
            "change_pct": -0.36,
            "projected": 27.9
          }
        ],
        "q4": [
          {
            "kpi": "eng_headcount",
            "change_pct": -12.0,
            "projected": 74.8
          },
          {
            "kpi": "feature_velocity",
            "change_pct": -3.6,
            "projected": 11.57
          },
          {
            "kpi": "product_nps",
            "change_pct": -1.44,
            "projected": 41.4
          },
          {
            "kpi": "platform_uptime",
            "change_pct": 0.36,
            "projected": 100.06
          },
          {
            "kpi": "win_rate",
            "change_pct": -0.36,
            "projected": 27.9
          }
        ]
      },
      "narrative": "Freezing engineering hiring for one quarter slows feature delivery by roughly 30% during the freeze period. Product NPS begins to decline within two quarters as the roadmap falls behind competitors. The win rate impact is modest (~3-4%) but compounds over time. The cost savings from delayed salaries are partially offset by reduced product competitiveness."
    },
    {
      "id": "accelerate_collections",
      "label": "Accelerate Collections (DSO -10 days)",
      "description": "What happens when we reduce days sales outstanding by 10 days?",
      "input_changes": [
        {
          "kpi": "dso",
          "change_absolute": -10
        }
      ],
      "cascade": [
        {
          "kpi": "dso",
          "baseline": 48,
          "change_pct": -20.83,
          "projected": 38.0,
          "lag_months": 0,
          "sigma": 0
        },
        {
          "kpi": "free_cash_flow",
          "baseline": 12.0,
          "change_pct": 5.83,
          "projected": 12.7,
          "lag_months": 1,
          "sigma": 0.05
        },
        {
          "kpi": "eng_headcount",
          "baseline": 85,
          "change_pct": 1.46,
          "projected": 86.24,
          "lag_months": 3,
          "sigma": 0.08
        },
        {
          "kpi": "marketing_spend",
          "baseline": 8.5,
          "change_pct": 1.17,
          "projected": 8.6,
          "lag_months": 3,
          "sigma": 0.06
        },
        {
          "kpi": "feature_velocity",
          "baseline": 12,
          "change_pct": 0.44,
          "projected": 12.05,
          "lag_months": 6,
          "sigma": 0.1
        },
        {
          "kpi": "mqls_per_month",
          "baseline": 1200,
          "change_pct": 0.76,
          "projected": 1209.1,
          "lag_months": 4,
          "sigma": 0.12
        },
        {
          "kpi": "brand_awareness",
          "baseline": 62.0,
          "change_pct": 0.47,
          "projected": 62.29,
          "lag_months": 6,
          "sigma": 0.08
        },
        {
          "kpi": "cac",
          "baseline": 8500,
          "change_pct": -0.35,
          "projected": 8470.25,
          "lag_months": 5,
          "sigma": 0.07
        },
        {
          "kpi": "product_nps",
          "baseline": 42,
          "change_pct": 0.18,
          "projected": 42.07,
          "lag_months": 8,
          "sigma": 0.08
        },
        {
          "kpi": "platform_uptime",
          "baseline": 99.7,
          "change_pct": -0.04,
          "projected": 99.66,
          "lag_months": 7,
          "sigma": 0.03
        },
        {
          "kpi": "pipeline_value",
          "baseline": 45.0,
          "change_pct": 0.42,
          "projected": 45.19,
          "lag_months": 6,
          "sigma": 0.1
        },
        {
          "kpi": "win_rate",
          "baseline": 28.0,
          "change_pct": -0.02,
          "projected": 27.99,
          "lag_months": 9,
          "sigma": 0.06
        }
      ],
      "quarterly": {
        "q1": [
          {
            "kpi": "dso",
            "change_pct": -20.83,
            "projected": 38.0
          },
          {
            "kpi": "free_cash_flow",
            "change_pct": 5.83,
            "projected": 12.7
          },
          {
            "kpi": "eng_headcount",
            "change_pct": 1.46,
            "projected": 86.24
          },
          {
            "kpi": "marketing_spend",
            "change_pct": 1.17,
            "projected": 8.6
          }
        ],
        "q2": [
          {
            "kpi": "dso",
            "change_pct": -20.83,
            "projected": 38.0
          },
          {
            "kpi": "free_cash_flow",
            "change_pct": 5.83,
            "projected": 12.7
          },
          {
            "kpi": "eng_headcount",
            "change_pct": 1.46,
            "projected": 86.24
          },
          {
            "kpi": "marketing_spend",
            "change_pct": 1.17,
            "projected": 8.6
          },
          {
            "kpi": "feature_velocity",
            "change_pct": 0.44,
            "projected": 12.05
          },
          {
            "kpi": "mqls_per_month",
            "change_pct": 0.76,
            "projected": 1209.1
          },
          {
            "kpi": "brand_awareness",
            "change_pct": 0.47,
            "projected": 62.29
          },
          {
            "kpi": "cac",
            "change_pct": -0.35,
            "projected": 8470.25
          },
          {
            "kpi": "pipeline_value",
            "change_pct": 0.42,
            "projected": 45.19
          }
        ],
        "q4": [
          {
            "kpi": "dso",
            "change_pct": -20.83,
            "projected": 38.0
          },
          {
            "kpi": "free_cash_flow",
            "change_pct": 5.83,
            "projected": 12.7
          },
          {
            "kpi": "eng_headcount",
            "change_pct": 1.46,
            "projected": 86.24
          },
          {
            "kpi": "marketing_spend",
            "change_pct": 1.17,
            "projected": 8.6
          },
          {
            "kpi": "feature_velocity",
            "change_pct": 0.44,
            "projected": 12.05
          },
          {
            "kpi": "mqls_per_month",
            "change_pct": 0.76,
            "projected": 1209.1
          },
          {
            "kpi": "brand_awareness",
            "change_pct": 0.47,
            "projected": 62.29
          },
          {
            "kpi": "cac",
            "change_pct": -0.35,
            "projected": 8470.25
          },
          {
            "kpi": "product_nps",
            "change_pct": 0.18,
            "projected": 42.07
          },
          {
            "kpi": "platform_uptime",
            "change_pct": -0.04,
            "projected": 99.66
          },
          {
            "kpi": "pipeline_value",
            "change_pct": 0.42,
            "projected": 45.19
          },
          {
            "kpi": "win_rate",
            "change_pct": -0.02,
            "projected": 27.99
          }
        ]
      },
      "narrative": "Reducing DSO by 10 days frees approximately $5.5M in working capital, improving free cash flow and reducing credit line reliance. The freed capital enables incremental reinvestment in engineering and marketing. This is one of the few decisions with predominantly positive cascading effects \u2014 the tradeoff is customer relationship friction from more aggressive collection terms."
    },
    {
      "id": "cut_operations_10",
      "label": "Cut Operations Budget by 10%",
      "description": "What happens when we reduce the operations budget by 10%?",
      "input_changes": [
        {
          "kpi": "ops_budget",
          "change_pct": -10
        }
      ],
      "cascade": [
        {
          "kpi": "ops_budget",
          "baseline": 12.0,
          "change_pct": -10.0,
          "projected": 10.8,
          "lag_months": 0,
          "sigma": 0
        },
        {
          "kpi": "fulfillment_rate",
          "baseline": 96.5,
          "change_pct": -7.0,
          "projected": 89.75,
          "lag_months": 1,
          "sigma": 0.12
        },
        {
          "kpi": "csat",
          "baseline": 4.2,
          "change_pct": -5.6,
          "projected": 3.96,
          "lag_months": 2,
          "sigma": 0.1
        },
        {
          "kpi": "churn_rate",
          "baseline": 1.8,
          "change_pct": 2.8,
          "projected": 1.85,
          "lag_months": 4,
          "sigma": 0.08
        },
        {
          "kpi": "pipeline_value",
          "baseline": 45.0,
          "change_pct": -0.98,
          "projected": 44.56,
          "lag_months": 7,
          "sigma": 0.06
        },
        {
          "kpi": "win_rate",
          "baseline": 28.0,
          "change_pct": 0.15,
          "projected": 28.04,
          "lag_months": 8,
          "sigma": 0.05
        }
      ],
      "quarterly": {
        "q1": [
          {
            "kpi": "ops_budget",
            "change_pct": -10.0,
            "projected": 10.8
          },
          {
            "kpi": "fulfillment_rate",
            "change_pct": -7.0,
            "projected": 89.75
          },
          {
            "kpi": "csat",
            "change_pct": -5.6,
            "projected": 3.96
          }
        ],
        "q2": [
          {
            "kpi": "ops_budget",
            "change_pct": -10.0,
            "projected": 10.8
          },
          {
            "kpi": "fulfillment_rate",
            "change_pct": -7.0,
            "projected": 89.75
          },
          {
            "kpi": "csat",
            "change_pct": -5.6,
            "projected": 3.96
          },
          {
            "kpi": "churn_rate",
            "change_pct": 2.8,
            "projected": 1.85
          }
        ],
        "q4": [
          {
            "kpi": "ops_budget",
            "change_pct": -10.0,
            "projected": 10.8
          },
          {
            "kpi": "fulfillment_rate",
            "change_pct": -7.0,
            "projected": 89.75
          },
          {
            "kpi": "csat",
            "change_pct": -5.6,
            "projected": 3.96
          },
          {
            "kpi": "churn_rate",
            "change_pct": 2.8,
            "projected": 1.85
          },
          {
            "kpi": "pipeline_value",
            "change_pct": -0.98,
            "projected": 44.56
          },
          {
            "kpi": "win_rate",
            "change_pct": 0.15,
            "projected": 28.04
          }
        ]
      },
      "narrative": "A 10% operations budget cut degrades fulfillment capacity, pushing the fulfillment rate below 90% within one quarter. Customer satisfaction drops measurably, driving churn up by an estimated 0.7 percentage points. The LTV impact from increased churn exceeds the budget savings within 12 months. Operations cuts have the longest and most damaging cascade of any scenario modeled."
    },
    {
      "id": "custom",
      "label": "Custom Scenario",
      "description": "User-defined scenario \u2014 adjust any division's input and watch the cascade.",
      "input_changes": [],
      "cascade": [],
      "quarterly": {
        "q1": [],
        "q2": [],
        "q4": []
      },
      "narrative": ""
    }
  ]
}

export const KPI_LABELS = {
  "pipeline_value": "Pipeline Value ($M)",
  "win_rate": "Win Rate (%)",
  "avg_deal_size": "Avg Deal Size ($K)",
  "sales_cycle_days": "Sales Cycle (days)",
  "marketing_spend": "Marketing Spend ($M)",
  "mqls_per_month": "MQLs/Month",
  "cac": "Customer Acquisition Cost ($)",
  "brand_awareness": "Brand Awareness Index",
  "eng_headcount": "Engineering Headcount",
  "feature_velocity": "Features Shipped/Quarter",
  "platform_uptime": "Platform Uptime (%)",
  "product_nps": "Product NPS",
  "ops_budget": "Operations Budget ($M)",
  "fulfillment_rate": "Fulfillment Rate (%)",
  "csat": "Customer Satisfaction",
  "churn_rate": "Monthly Churn Rate (%)",
  "dso": "DSO (days)",
  "operating_margin": "Operating Margin (%)",
  "free_cash_flow": "Free Cash Flow ($M)"
}

export const KPI_DIVISIONS = {
  "pipeline_value": "Sales",
  "win_rate": "Sales",
  "avg_deal_size": "Sales",
  "sales_cycle_days": "Sales",
  "marketing_spend": "Marketing",
  "mqls_per_month": "Marketing",
  "cac": "Marketing",
  "brand_awareness": "Marketing",
  "eng_headcount": "Engineering & Product",
  "feature_velocity": "Engineering & Product",
  "platform_uptime": "Engineering & Product",
  "product_nps": "Engineering & Product",
  "ops_budget": "Operations",
  "fulfillment_rate": "Operations",
  "csat": "Operations",
  "churn_rate": "Operations",
  "dso": "Finance",
  "operating_margin": "Finance",
  "free_cash_flow": "Finance"
}
