"""Generate fallbackData.js from the pipeline output.

Run once after data generation to create static fallback data
for the Executive Command Center. Output is committed to git.
"""

import os
import json

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Read the pipeline code
with open(os.path.join(ROOT, 'src', 'projects', 'command-center', 'pipeline_etl.py')) as f:
    code = f.read()

# Replace /data/ paths with public/data/ for local execution
code = code.replace("'/data/", f"'{os.path.join(ROOT, 'public', 'data')}/")

exec(code)

# Write as JS module
output_path = os.path.join(ROOT, 'src', 'projects', 'command-center', 'fallbackData.js')
with open(output_path, 'w') as f:
    f.write('// Auto-generated by data-generation/project1/generate_fallback.py\n')
    f.write('// Do not edit manually — regenerate with: python generate_fallback.py\n\n')
    f.write('export const FALLBACK_DATA = ')
    json.dump(result, f, indent=2)
    f.write('\n')

print(f'Fallback data generated: {os.path.getsize(output_path):,} bytes -> {output_path}')
