// Auto-generated by data-generation/project3/generate_fallback.py
// Do not edit manually — regenerate with: python generate_fallback.py

export const FALLBACK_DATA = {
  "summary": {
    "total_budget": 33324618.200000003,
    "total_actual": 36616908.11,
    "total_variance": 3292289.9099999964,
    "total_variance_pct": 9.9,
    "anomaly_count": 48,
    "transactions_analyzed": 5161,
    "highest_risk_department": "Operations",
    "highest_risk_pct": 35.1,
    "variance_sparkline": [
      454395.89,
      201292.48,
      411466.15,
      169545.44,
      197718.33,
      276390.41,
      329829.18,
      176081.82,
      313569.63,
      185009.47,
      259220.86,
      317770.25
    ]
  },
  "heatmap": [
    {
      "id": "Engineering",
      "data": [
        {
          "x": "Jan 25",
          "y": 42.1,
          "hasAnomaly": true
        },
        {
          "x": "Feb 25",
          "y": -1.2,
          "hasAnomaly": false
        },
        {
          "x": "Mar 25",
          "y": 7.5,
          "hasAnomaly": true
        },
        {
          "x": "Apr 25",
          "y": -1.0,
          "hasAnomaly": false
        },
        {
          "x": "May 25",
          "y": -0.1,
          "hasAnomaly": false
        },
        {
          "x": "Jun 25",
          "y": 1.3,
          "hasAnomaly": true
        },
        {
          "x": "Jul 25",
          "y": 1.4,
          "hasAnomaly": false
        },
        {
          "x": "Aug 25",
          "y": 0.0,
          "hasAnomaly": false
        },
        {
          "x": "Sep 25",
          "y": 0.6,
          "hasAnomaly": false
        },
        {
          "x": "Oct 25",
          "y": 1.6,
          "hasAnomaly": false
        },
        {
          "x": "Nov 25",
          "y": 6.3,
          "hasAnomaly": true
        },
        {
          "x": "Dec 25",
          "y": 0.7,
          "hasAnomaly": false
        }
      ]
    },
    {
      "id": "Finance",
      "data": [
        {
          "x": "Jan 25",
          "y": 22.8,
          "hasAnomaly": true
        },
        {
          "x": "Feb 25",
          "y": 6.3,
          "hasAnomaly": true
        },
        {
          "x": "Mar 25",
          "y": 45.2,
          "hasAnomaly": true
        },
        {
          "x": "Apr 25",
          "y": -0.4,
          "hasAnomaly": false
        },
        {
          "x": "May 25",
          "y": 22.3,
          "hasAnomaly": true
        },
        {
          "x": "Jun 25",
          "y": 12.9,
          "hasAnomaly": true
        },
        {
          "x": "Jul 25",
          "y": 45.0,
          "hasAnomaly": true
        },
        {
          "x": "Aug 25",
          "y": 26.4,
          "hasAnomaly": true
        },
        {
          "x": "Sep 25",
          "y": 14.6,
          "hasAnomaly": true
        },
        {
          "x": "Oct 25",
          "y": 2.7,
          "hasAnomaly": false
        },
        {
          "x": "Nov 25",
          "y": 23.5,
          "hasAnomaly": true
        },
        {
          "x": "Dec 25",
          "y": 18.3,
          "hasAnomaly": true
        }
      ]
    },
    {
      "id": "Marketing",
      "data": [
        {
          "x": "Jan 25",
          "y": 10.7,
          "hasAnomaly": true
        },
        {
          "x": "Feb 25",
          "y": 1.1,
          "hasAnomaly": false
        },
        {
          "x": "Mar 25",
          "y": 0.5,
          "hasAnomaly": false
        },
        {
          "x": "Apr 25",
          "y": 34.6,
          "hasAnomaly": true
        },
        {
          "x": "May 25",
          "y": 6.6,
          "hasAnomaly": true
        },
        {
          "x": "Jun 25",
          "y": 5.9,
          "hasAnomaly": true
        },
        {
          "x": "Jul 25",
          "y": -0.1,
          "hasAnomaly": false
        },
        {
          "x": "Aug 25",
          "y": -0.2,
          "hasAnomaly": false
        },
        {
          "x": "Sep 25",
          "y": 8.3,
          "hasAnomaly": true
        },
        {
          "x": "Oct 25",
          "y": 1.7,
          "hasAnomaly": false
        },
        {
          "x": "Nov 25",
          "y": 3.5,
          "hasAnomaly": false
        },
        {
          "x": "Dec 25",
          "y": 7.3,
          "hasAnomaly": true
        }
      ]
    },
    {
      "id": "Operations",
      "data": [
        {
          "x": "Jan 25",
          "y": 14.9,
          "hasAnomaly": true
        },
        {
          "x": "Feb 25",
          "y": 21.1,
          "hasAnomaly": true
        },
        {
          "x": "Mar 25",
          "y": 29.6,
          "hasAnomaly": true
        },
        {
          "x": "Apr 25",
          "y": 15.7,
          "hasAnomaly": true
        },
        {
          "x": "May 25",
          "y": 18.8,
          "hasAnomaly": true
        },
        {
          "x": "Jun 25",
          "y": 24.5,
          "hasAnomaly": true
        },
        {
          "x": "Jul 25",
          "y": 16.0,
          "hasAnomaly": true
        },
        {
          "x": "Aug 25",
          "y": 13.8,
          "hasAnomaly": true
        },
        {
          "x": "Sep 25",
          "y": 24.2,
          "hasAnomaly": true
        },
        {
          "x": "Oct 25",
          "y": 14.1,
          "hasAnomaly": true
        },
        {
          "x": "Nov 25",
          "y": 13.1,
          "hasAnomaly": true
        },
        {
          "x": "Dec 25",
          "y": 26.9,
          "hasAnomaly": true
        }
      ]
    },
    {
      "id": "Sales",
      "data": [
        {
          "x": "Jan 25",
          "y": 0.8,
          "hasAnomaly": false
        },
        {
          "x": "Feb 25",
          "y": 0.2,
          "hasAnomaly": false
        },
        {
          "x": "Mar 25",
          "y": 1.6,
          "hasAnomaly": false
        },
        {
          "x": "Apr 25",
          "y": 0.5,
          "hasAnomaly": false
        },
        {
          "x": "May 25",
          "y": 1.8,
          "hasAnomaly": false
        },
        {
          "x": "Jun 25",
          "y": 1.2,
          "hasAnomaly": false
        },
        {
          "x": "Jul 25",
          "y": 5.8,
          "hasAnomaly": false
        },
        {
          "x": "Aug 25",
          "y": 2.4,
          "hasAnomaly": false
        },
        {
          "x": "Sep 25",
          "y": 7.8,
          "hasAnomaly": true
        },
        {
          "x": "Oct 25",
          "y": 6.3,
          "hasAnomaly": false
        },
        {
          "x": "Nov 25",
          "y": 4.8,
          "hasAnomaly": false
        },
        {
          "x": "Dec 25",
          "y": 8.2,
          "hasAnomaly": true
        }
      ]
    }
  ],
  "by_department": [
    {
      "department": "Engineering",
      "budget": 10114650.27,
      "actual": 10440404.13
    },
    {
      "department": "Finance",
      "budget": 3954096.05,
      "actual": 4656131.67
    },
    {
      "department": "Marketing",
      "budget": 6403699.17,
      "actual": 6728676.57
    },
    {
      "department": "Operations",
      "budget": 5095627.63,
      "actual": 6883139.49
    },
    {
      "department": "Sales",
      "budget": 7756545.08,
      "actual": 7908556.25
    }
  ],
  "time_series": [
    {
      "month": "Jan 25",
      "budget": 2639478.43,
      "actual": 3093874.32,
      "anomaly_count": 6
    },
    {
      "month": "Feb 25",
      "budget": 2654163.0,
      "actual": 2855455.48,
      "anomaly_count": 4
    },
    {
      "month": "Mar 25",
      "budget": 2761264.43,
      "actual": 3172730.58,
      "anomaly_count": 6
    },
    {
      "month": "Apr 25",
      "budget": 2753930.3,
      "actual": 2923475.74,
      "anomaly_count": 2
    },
    {
      "month": "May 25",
      "budget": 2727407.75,
      "actual": 2925126.08,
      "anomaly_count": 4
    },
    {
      "month": "Jun 25",
      "budget": 2743390.91,
      "actual": 3019781.32,
      "anomaly_count": 5
    },
    {
      "month": "Jul 25",
      "budget": 2742650.31,
      "actual": 3072479.49,
      "anomaly_count": 3
    },
    {
      "month": "Aug 25",
      "budget": 2718604.33,
      "actual": 2894686.15,
      "anomaly_count": 3
    },
    {
      "month": "Sep 25",
      "budget": 2872515.89,
      "actual": 3186085.52,
      "anomaly_count": 5
    },
    {
      "month": "Oct 25",
      "budget": 2878217.09,
      "actual": 3063226.56,
      "anomaly_count": 1
    },
    {
      "month": "Nov 25",
      "budget": 2901335.22,
      "actual": 3160556.08,
      "anomaly_count": 3
    },
    {
      "month": "Dec 25",
      "budget": 2931660.54,
      "actual": 3249430.79,
      "anomaly_count": 6
    }
  ],
  "anomalies": [
    {
      "department": "Engineering",
      "line_item": "Software Licenses",
      "month": "2025-01",
      "budget": 35058.12,
      "actual": 266704.26,
      "variance_abs": 231646.14,
      "variance_pct": 660.7,
      "type": "seasonal_spike",
      "severity": "medium",
      "explanation": "Seasonal spike: Software Licenses in Engineering exceeded budget by 661% in 2025-01."
    },
    {
      "department": "Finance",
      "line_item": "ERP Software",
      "month": "2025-07",
      "budget": 25157.92,
      "actual": 199901.59,
      "variance_abs": 174743.67,
      "variance_pct": 694.6,
      "type": "one_time_event",
      "severity": "low",
      "explanation": "Unusual activity: ERP Software in Finance was $174,744 over budget (695%) in 2025-07."
    },
    {
      "department": "Finance",
      "line_item": "Audit & Compliance",
      "month": "2025-03",
      "budget": 30353.09,
      "actual": 185585.03,
      "variance_abs": 155231.94,
      "variance_pct": 511.4,
      "type": "one_time_event",
      "severity": "low",
      "explanation": "Unusual activity: Audit & Compliance in Finance was $155,232 over budget (511%) in 2025-03."
    },
    {
      "department": "Operations",
      "line_item": "Facilities & Rent",
      "month": "2025-02",
      "budget": 75759.57,
      "actual": 210678.26,
      "variance_abs": 134918.69,
      "variance_pct": 178.1,
      "type": "trending_overspend",
      "severity": "high",
      "explanation": "Trending overspend: Facilities & Rent costs drifting +7%/month. Cumulative excess: $258,285."
    },
    {
      "department": "Operations",
      "line_item": "Facilities & Rent",
      "month": "2025-10",
      "budget": 74028.39,
      "actual": 207977.56,
      "variance_abs": 133949.17,
      "variance_pct": 180.9,
      "type": "trending_overspend",
      "severity": "high",
      "explanation": "Trending overspend: Facilities & Rent costs drifting +7%/month. Cumulative excess: $1,262,097."
    },
    {
      "department": "Operations",
      "line_item": "Facilities & Rent",
      "month": "2025-04",
      "budget": 72806.58,
      "actual": 205420.24,
      "variance_abs": 132613.66,
      "variance_pct": 182.1,
      "type": "trending_overspend",
      "severity": "high",
      "explanation": "Trending overspend: Facilities & Rent costs drifting +7%/month. Cumulative excess: $517,717."
    },
    {
      "department": "Operations",
      "line_item": "Facilities & Rent",
      "month": "2025-05",
      "budget": 76215.24,
      "actual": 204984.67,
      "variance_abs": 128769.43,
      "variance_pct": 169.0,
      "type": "trending_overspend",
      "severity": "high",
      "explanation": "Trending overspend: Facilities & Rent costs drifting +7%/month. Cumulative excess: $646,487."
    },
    {
      "department": "Operations",
      "line_item": "Facilities & Rent",
      "month": "2025-03",
      "budget": 69616.56,
      "actual": 196435.23,
      "variance_abs": 126818.67,
      "variance_pct": 182.2,
      "type": "trending_overspend",
      "severity": "high",
      "explanation": "Trending overspend: Facilities & Rent costs drifting +7%/month. Cumulative excess: $385,103."
    },
    {
      "department": "Operations",
      "line_item": "Facilities & Rent",
      "month": "2025-11",
      "budget": 72790.58,
      "actual": 199234.28,
      "variance_abs": 126443.7,
      "variance_pct": 173.7,
      "type": "trending_overspend",
      "severity": "high",
      "explanation": "Trending overspend: Facilities & Rent costs drifting +7%/month. Cumulative excess: $1,388,541."
    },
    {
      "department": "Operations",
      "line_item": "Facilities & Rent",
      "month": "2025-06",
      "budget": 68685.65,
      "actual": 192300.51,
      "variance_abs": 123614.86,
      "variance_pct": 180.0,
      "type": "trending_overspend",
      "severity": "high",
      "explanation": "Trending overspend: Facilities & Rent costs drifting +7%/month. Cumulative excess: $770,101."
    },
    {
      "department": "Operations",
      "line_item": "Facilities & Rent",
      "month": "2025-01",
      "budget": 72777.12,
      "actual": 196143.19,
      "variance_abs": 123366.07,
      "variance_pct": 169.5,
      "type": "trending_overspend",
      "severity": "high",
      "explanation": "Trending overspend: Facilities & Rent costs drifting +7%/month. Cumulative excess: $123,366."
    },
    {
      "department": "Operations",
      "line_item": "Facilities & Rent",
      "month": "2025-09",
      "budget": 71138.03,
      "actual": 193266.01,
      "variance_abs": 122127.98,
      "variance_pct": 171.7,
      "type": "trending_overspend",
      "severity": "high",
      "explanation": "Trending overspend: Facilities & Rent costs drifting +7%/month. Cumulative excess: $1,128,148."
    },
    {
      "department": "Operations",
      "line_item": "Facilities & Rent",
      "month": "2025-08",
      "budget": 71348.29,
      "actual": 192226.25,
      "variance_abs": 120877.96,
      "variance_pct": 169.4,
      "type": "trending_overspend",
      "severity": "high",
      "explanation": "Trending overspend: Facilities & Rent costs drifting +7%/month. Cumulative excess: $1,006,020."
    },
    {
      "department": "Operations",
      "line_item": "Facilities & Rent",
      "month": "2025-12",
      "budget": 68418.55,
      "actual": 184699.29,
      "variance_abs": 116280.74,
      "variance_pct": 170.0,
      "type": "trending_overspend",
      "severity": "high",
      "explanation": "Trending overspend: Facilities & Rent costs drifting +7%/month. Cumulative excess: $1,504,822."
    },
    {
      "department": "Operations",
      "line_item": "Facilities & Rent",
      "month": "2025-07",
      "budget": 69489.31,
      "actual": 184530.02,
      "variance_abs": 115040.71,
      "variance_pct": 165.6,
      "type": "trending_overspend",
      "severity": "high",
      "explanation": "Trending overspend: Facilities & Rent costs drifting +7%/month. Cumulative excess: $885,142."
    },
    {
      "department": "Marketing",
      "line_item": "Event Sponsorships",
      "month": "2025-09",
      "budget": 61108.59,
      "actual": 123556.67,
      "variance_abs": 62448.08,
      "variance_pct": 102.2,
      "type": "one_time_event",
      "severity": "low",
      "explanation": "Unusual activity: Event Sponsorships in Marketing was $62,448 over budget (102%) in 2025-09."
    },
    {
      "department": "Finance",
      "line_item": "Insurance Premiums",
      "month": "2025-03",
      "budget": 22461.16,
      "actual": 70226.19,
      "variance_abs": 47765.03,
      "variance_pct": 212.7,
      "type": "one_time_event",
      "severity": "low",
      "explanation": "Unusual activity: Insurance Premiums in Finance was $47,765 over budget (213%) in 2025-03."
    },
    {
      "department": "Finance",
      "line_item": "Insurance Premiums",
      "month": "2025-12",
      "budget": 22331.12,
      "actual": 69559.83,
      "variance_abs": 47228.71,
      "variance_pct": 211.5,
      "type": "seasonal_spike",
      "severity": "medium",
      "explanation": "Seasonal spike: Insurance Premiums in Finance exceeded budget by 211% in 2025-12."
    },
    {
      "department": "Finance",
      "line_item": "Insurance Premiums",
      "month": "2025-06",
      "budget": 22558.98,
      "actual": 68968.71,
      "variance_abs": 46409.73,
      "variance_pct": 205.7,
      "type": "one_time_event",
      "severity": "low",
      "explanation": "Unusual activity: Insurance Premiums in Finance was $46,410 over budget (206%) in 2025-06."
    },
    {
      "department": "Finance",
      "line_item": "Insurance Premiums",
      "month": "2025-09",
      "budget": 21618.77,
      "actual": 66092.99,
      "variance_abs": 44474.22,
      "variance_pct": 205.7,
      "type": "one_time_event",
      "severity": "low",
      "explanation": "Unusual activity: Insurance Premiums in Finance was $44,474 over budget (206%) in 2025-09."
    },
    {
      "department": "Operations",
      "line_item": "Insurance",
      "month": "2025-12",
      "budget": 19178.39,
      "actual": 61715.15,
      "variance_abs": 42536.76,
      "variance_pct": 221.8,
      "type": "seasonal_spike",
      "severity": "medium",
      "explanation": "Seasonal spike: Insurance in Operations exceeded budget by 222% in 2025-12."
    },
    {
      "department": "Operations",
      "line_item": "Insurance",
      "month": "2025-06",
      "budget": 19683.33,
      "actual": 61749.34,
      "variance_abs": 42066.01,
      "variance_pct": 213.7,
      "type": "one_time_event",
      "severity": "low",
      "explanation": "Unusual activity: Insurance in Operations was $42,066 over budget (214%) in 2025-06."
    },
    {
      "department": "Operations",
      "line_item": "Insurance",
      "month": "2025-09",
      "budget": 19283.33,
      "actual": 60990.12,
      "variance_abs": 41706.79,
      "variance_pct": 216.3,
      "type": "one_time_event",
      "severity": "low",
      "explanation": "Unusual activity: Insurance in Operations was $41,707 over budget (216%) in 2025-09."
    },
    {
      "department": "Marketing",
      "line_item": "Digital Advertising",
      "month": "2025-12",
      "budget": 139959.86,
      "actual": 180773.11,
      "variance_abs": 40813.25,
      "variance_pct": 29.2,
      "type": "trending_overspend",
      "severity": "high",
      "explanation": "Trending overspend: Digital Advertising costs drifting +7%/month. Cumulative excess: $121,100."
    },
    {
      "department": "Operations",
      "line_item": "Insurance",
      "month": "2025-03",
      "budget": 19068.8,
      "actual": 57749.31,
      "variance_abs": 38680.51,
      "variance_pct": 202.8,
      "type": "one_time_event",
      "severity": "low",
      "explanation": "Unusual activity: Insurance in Operations was $38,681 over budget (203%) in 2025-03."
    },
    {
      "department": "Engineering",
      "line_item": "Cloud Hosting (AWS/GCP)",
      "month": "2025-06",
      "budget": 123090.81,
      "actual": 160047.39,
      "variance_abs": 36956.58,
      "variance_pct": 30.0,
      "type": "one_time_event",
      "severity": "low",
      "explanation": "Unusual activity: Cloud Hosting (AWS/GCP) in Engineering was $36,957 over budget (30%) in 2025-06."
    },
    {
      "department": "Marketing",
      "line_item": "Digital Advertising",
      "month": "2025-01",
      "budget": 78074.89,
      "actual": 111713.98,
      "variance_abs": 33639.09,
      "variance_pct": 43.1,
      "type": "trending_overspend",
      "severity": "high",
      "explanation": "Trending overspend: Digital Advertising costs drifting +7%/month. Cumulative excess: $33,639."
    },
    {
      "department": "Marketing",
      "line_item": "Content Production",
      "month": "2025-06",
      "budget": 34937.35,
      "actual": 63974.6,
      "variance_abs": 29037.25,
      "variance_pct": 83.1,
      "type": "trending_overspend",
      "severity": "high",
      "explanation": "Trending overspend: Content Production costs drifting +15%/month. Cumulative excess: $22,105."
    },
    {
      "department": "Finance",
      "line_item": "Accounts Receivable Services",
      "month": "2025-08",
      "budget": 9029.3,
      "actual": 37617.07,
      "variance_abs": 28587.77,
      "variance_pct": 316.6,
      "type": "threshold_cluster",
      "severity": "medium",
      "explanation": "Threshold clustering: Accounts Receivable Services has a transaction at $29,543 \u2014 98% of Finance's $30,000 approval limit."
    },
    {
      "department": "Finance",
      "line_item": "Audit & Compliance",
      "month": "2025-02",
      "budget": 28731.11,
      "actual": 56852.9,
      "variance_abs": 28121.79,
      "variance_pct": 97.9,
      "type": "threshold_cluster",
      "severity": "medium",
      "explanation": "Threshold clustering: Audit & Compliance has a transaction at $28,834 \u2014 96% of Finance's $30,000 approval limit."
    },
    {
      "department": "Finance",
      "line_item": "Banking Fees",
      "month": "2025-05",
      "budget": 7479.29,
      "actual": 34042.97,
      "variance_abs": 26563.68,
      "variance_pct": 355.2,
      "type": "threshold_cluster",
      "severity": "medium",
      "explanation": "Threshold clustering: Banking Fees has a transaction at $27,958 \u2014 93% of Finance's $30,000 approval limit."
    },
    {
      "department": "Finance",
      "line_item": "Investor Relations",
      "month": "2025-01",
      "budget": 7562.39,
      "actual": 34078.06,
      "variance_abs": 26515.67,
      "variance_pct": 350.6,
      "type": "threshold_cluster",
      "severity": "medium",
      "explanation": "Threshold clustering: Investor Relations has a transaction at $28,820 \u2014 96% of Finance's $30,000 approval limit."
    },
    {
      "department": "Finance",
      "line_item": "Audit & Compliance",
      "month": "2025-08",
      "budget": 28624.68,
      "actual": 54524.12,
      "variance_abs": 25899.44,
      "variance_pct": 90.5,
      "type": "threshold_cluster",
      "severity": "medium",
      "explanation": "Threshold clustering: Audit & Compliance has a transaction at $28,328 \u2014 94% of Finance's $30,000 approval limit."
    },
    {
      "department": "Finance",
      "line_item": "Investor Relations",
      "month": "2025-11",
      "budget": 7306.42,
      "actual": 31160.37,
      "variance_abs": 23853.95,
      "variance_pct": 326.5,
      "type": "threshold_cluster",
      "severity": "medium",
      "explanation": "Threshold clustering: Investor Relations has a transaction at $27,817 \u2014 93% of Finance's $30,000 approval limit."
    },
    {
      "department": "Engineering",
      "line_item": "Hardware & Equipment",
      "month": "2025-11",
      "budget": 29360.03,
      "actual": 53188.39,
      "variance_abs": 23828.36,
      "variance_pct": 81.2,
      "type": "seasonal_spike",
      "severity": "medium",
      "explanation": "Seasonal spike: Hardware & Equipment in Engineering exceeded budget by 81% in 2025-11."
    },
    {
      "department": "Engineering",
      "line_item": "Dev Tools & CI/CD",
      "month": "2025-03",
      "budget": 15701.29,
      "actual": 38545.26,
      "variance_abs": 22843.97,
      "variance_pct": 145.5,
      "type": "threshold_cluster",
      "severity": "medium",
      "explanation": "Threshold clustering: Dev Tools & CI/CD has a transaction at $23,282 \u2014 93% of Engineering's $25,000 approval limit."
    },
    {
      "department": "Marketing",
      "line_item": "Print Materials",
      "month": "2025-04",
      "budget": 3692.71,
      "actual": 22823.62,
      "variance_abs": 19130.91,
      "variance_pct": 518.1,
      "type": "threshold_cluster",
      "severity": "medium",
      "explanation": "Threshold clustering: Print Materials has a transaction at $19,664 \u2014 98% of Marketing's $20,000 approval limit."
    },
    {
      "department": "Marketing",
      "line_item": "Analytics Tools",
      "month": "2025-01",
      "budget": 11580.22,
      "actual": 26879.5,
      "variance_abs": 15299.28,
      "variance_pct": 132.1,
      "type": "threshold_cluster",
      "severity": "medium",
      "explanation": "Threshold clustering: Analytics Tools has a transaction at $18,781 \u2014 94% of Marketing's $20,000 approval limit."
    },
    {
      "department": "Marketing",
      "line_item": "Photography & Video",
      "month": "2025-05",
      "budget": 15153.62,
      "actual": 29008.78,
      "variance_abs": 13855.16,
      "variance_pct": 91.4,
      "type": "threshold_cluster",
      "severity": "medium",
      "explanation": "Threshold clustering: Photography & Video has a transaction at $18,683 \u2014 93% of Marketing's $20,000 approval limit."
    },
    {
      "department": "Marketing",
      "line_item": "Marketing Automation Software",
      "month": "2025-12",
      "budget": 19547.24,
      "actual": 32773.99,
      "variance_abs": 13226.75,
      "variance_pct": 67.7,
      "type": "seasonal_spike",
      "severity": "medium",
      "explanation": "Seasonal spike: Marketing Automation Software in Marketing exceeded budget by 68% in 2025-12."
    },
    {
      "department": "Sales",
      "line_item": "Entertainment & Meals",
      "month": "2025-09",
      "budget": 15662.28,
      "actual": 28017.56,
      "variance_abs": 12355.28,
      "variance_pct": 78.9,
      "type": "threshold_cluster",
      "severity": "medium",
      "explanation": "Threshold clustering: Entertainment & Meals has a transaction at $13,924 \u2014 93% of Sales's $15,000 approval limit."
    },
    {
      "department": "Operations",
      "line_item": "Insurance",
      "month": "2025-02",
      "budget": 19803.32,
      "actual": 30605.7,
      "variance_abs": 10802.38,
      "variance_pct": 54.5,
      "type": "seasonal_spike",
      "severity": "medium",
      "explanation": "Seasonal spike: Insurance in Operations exceeded budget by 55% in 2025-02."
    },
    {
      "department": "Operations",
      "line_item": "Returns Processing",
      "month": "2025-05",
      "budget": 7623.83,
      "actual": 16722.36,
      "variance_abs": 9098.53,
      "variance_pct": 119.3,
      "type": "threshold_cluster",
      "severity": "medium",
      "explanation": "Threshold clustering: Returns Processing has a transaction at $9,639 \u2014 96% of Operations's $10,000 approval limit."
    },
    {
      "department": "Operations",
      "line_item": "Insurance",
      "month": "2025-01",
      "budget": 18707.0,
      "actual": 27128.68,
      "variance_abs": 8421.68,
      "variance_pct": 45.0,
      "type": "seasonal_spike",
      "severity": "medium",
      "explanation": "Seasonal spike: Insurance in Operations exceeded budget by 45% in 2025-01."
    },
    {
      "department": "Operations",
      "line_item": "Vendor Management",
      "month": "2025-07",
      "budget": 11758.12,
      "actual": 20110.46,
      "variance_abs": 8352.34,
      "variance_pct": 71.0,
      "type": "threshold_cluster",
      "severity": "medium",
      "explanation": "Threshold clustering: Vendor Management has a transaction at $9,704 \u2014 97% of Operations's $10,000 approval limit."
    },
    {
      "department": "Operations",
      "line_item": "Vendor Management",
      "month": "2025-03",
      "budget": 11800.22,
      "actual": 20076.17,
      "variance_abs": 8275.95,
      "variance_pct": 70.1,
      "type": "threshold_cluster",
      "severity": "medium",
      "explanation": "Threshold clustering: Vendor Management has a transaction at $9,502 \u2014 95% of Operations's $10,000 approval limit."
    },
    {
      "department": "Sales",
      "line_item": "Sales Enablement Tools",
      "month": "2025-12",
      "budget": 13087.23,
      "actual": 20885.69,
      "variance_abs": 7798.46,
      "variance_pct": 59.6,
      "type": "threshold_cluster",
      "severity": "medium",
      "explanation": "Threshold clustering: Sales Enablement Tools has a transaction at $13,892 \u2014 93% of Sales's $15,000 approval limit."
    },
    {
      "department": "Operations",
      "line_item": "Inventory Management System",
      "month": "2025-02",
      "budget": 11495.63,
      "actual": 18744.12,
      "variance_abs": 7248.49,
      "variance_pct": 63.1,
      "type": "seasonal_spike",
      "severity": "medium",
      "explanation": "Seasonal spike: Inventory Management System in Operations exceeded budget by 63% in 2025-02."
    }
  ],
  "raw_counts": {
    "budget_rows": 960,
    "actual_transactions": 5161,
    "departments": 5,
    "vendors": 263
  }
}
