"""Generate fallbackData.js from org_model.json and scenario_presets.json.

Run once after data generation to create static fallback data
for the Decision Impact Analyzer. Output is committed to git.
"""

import os
import json

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
PUBLIC_DATA = os.path.join(ROOT, "public", "data")

# Read source JSON files
with open(os.path.join(PUBLIC_DATA, "org_model.json")) as f:
    org_model = json.load(f)

with open(os.path.join(PUBLIC_DATA, "scenario_presets.json")) as f:
    scenario_presets = json.load(f)

# Build KPI label lookup from org model
kpi_labels = {}
kpi_divisions = {}
for div_key, div in org_model["divisions"].items():
    for kpi in div["kpis"]:
        kpi_labels[kpi["id"]] = kpi["label"]
        kpi_divisions[kpi["id"]] = div["label"]

# Write as JS module
output_path = os.path.join(ROOT, "src", "projects", "decision-impact", "fallbackData.js")
os.makedirs(os.path.dirname(output_path), exist_ok=True)

with open(output_path, "w") as f:
    f.write("// Auto-generated by data-generation/project2/generate_fallback.py\n")
    f.write("// Do not edit manually — regenerate with: python generate_fallback.py\n\n")
    f.write("export const FALLBACK_ORG_MODEL = ")
    json.dump(org_model, f, indent=2)
    f.write("\n\n")
    f.write("export const FALLBACK_SCENARIOS = ")
    json.dump(scenario_presets, f, indent=2)
    f.write("\n\n")
    f.write("export const KPI_LABELS = ")
    json.dump(kpi_labels, f, indent=2)
    f.write("\n\n")
    f.write("export const KPI_DIVISIONS = ")
    json.dump(kpi_divisions, f, indent=2)
    f.write("\n")

print(f"Fallback data generated: {os.path.getsize(output_path):,} bytes -> {output_path}")
