// Auto-generated by data-generation/project4/generate_fallback.py
// Do not edit manually — regenerate with: python generate_fallback.py
//
// Seeds the never-blank first paint + offline preset switching. Each preset carries
// its own editable order book and a precomputed result identical to capacity_engine.py.

export const FALLBACK_BACKLOG = [
  {
    "id": "ORD-2401",
    "name": "Offshore module skid",
    "customer": "Maasvlakte Terminals",
    "market_segment": "Oil & Gas",
    "contract_value": 6400000,
    "gross_margin_pct": 0.18,
    "duration_months": 8,
    "order_intake_date": "2026-01",
    "promised_delivery_date": "2026-11",
    "priority": 1,
    "status": "in_progress"
  },
  {
    "id": "ORD-2402",
    "name": "Refinery heat exchanger",
    "customer": "Maasvlakte Terminals",
    "market_segment": "Petrochemical",
    "contract_value": 3100000,
    "gross_margin_pct": 0.22,
    "duration_months": 7,
    "order_intake_date": "2026-01",
    "promised_delivery_date": "2026-09",
    "priority": 1,
    "status": "in_progress"
  },
  {
    "id": "ORD-2403",
    "name": "Cryogenic storage tank",
    "customer": "Veridian Chemicals",
    "market_segment": "Oil & Gas",
    "contract_value": 3500000,
    "gross_margin_pct": 0.19,
    "duration_months": 7,
    "order_intake_date": "2026-02",
    "promised_delivery_date": "2026-12",
    "priority": 1,
    "status": "backlog"
  },
  {
    "id": "ORD-2404",
    "name": "Pressure vessel array",
    "customer": "Caspian Energy Group",
    "market_segment": "Petrochemical",
    "contract_value": 2300000,
    "gross_margin_pct": 0.21,
    "duration_months": 6,
    "order_intake_date": "2026-01",
    "promised_delivery_date": "2026-11",
    "priority": 2,
    "status": "in_progress"
  },
  {
    "id": "ORD-2405",
    "name": "Modular substation",
    "customer": "Caspian Energy Group",
    "market_segment": "Power Generation",
    "contract_value": 2650000,
    "gross_margin_pct": 0.2,
    "duration_months": 6,
    "order_intake_date": "2026-03",
    "promised_delivery_date": "2027-01",
    "priority": 2,
    "status": "backlog"
  },
  {
    "id": "ORD-2406",
    "name": "Turbine enclosure",
    "customer": "Alpine Process Tech",
    "market_segment": "Power Generation",
    "contract_value": 1500000,
    "gross_margin_pct": 0.24,
    "duration_months": 5,
    "order_intake_date": "2026-02",
    "promised_delivery_date": "2026-12",
    "priority": 2,
    "status": "backlog"
  },
  {
    "id": "ORD-2407",
    "name": "Marine propulsion frame",
    "customer": "Adriatic Offshore",
    "market_segment": "Marine",
    "contract_value": 1050000,
    "gross_margin_pct": 0.27,
    "duration_months": 4,
    "order_intake_date": "2026-01",
    "promised_delivery_date": "2026-10",
    "priority": 2,
    "status": "in_progress"
  },
  {
    "id": "ORD-2408",
    "name": "Flare stack package",
    "customer": "Donau Industrial",
    "market_segment": "Oil & Gas",
    "contract_value": 1200000,
    "gross_margin_pct": 0.26,
    "duration_months": 4,
    "order_intake_date": "2026-03",
    "promised_delivery_date": "2027-01",
    "priority": 3,
    "status": "backlog"
  },
  {
    "id": "ORD-2409",
    "name": "Reactor internals",
    "customer": "Caspian Energy Group",
    "market_segment": "Petrochemical",
    "contract_value": 4700000,
    "gross_margin_pct": 0.17,
    "duration_months": 8,
    "order_intake_date": "2026-04",
    "promised_delivery_date": "2027-05",
    "priority": 1,
    "status": "backlog"
  },
  {
    "id": "ORD-2410",
    "name": "Pipe rack & valve skid",
    "customer": "Adriatic Offshore",
    "market_segment": "Oil & Gas",
    "contract_value": 780000,
    "gross_margin_pct": 0.3,
    "duration_months": 3,
    "order_intake_date": "2026-02",
    "promised_delivery_date": "2026-11",
    "priority": 3,
    "status": "backlog"
  },
  {
    "id": "ORD-2411",
    "name": "Heat recovery unit",
    "customer": "Baltic Power Systems",
    "market_segment": "Power Generation",
    "contract_value": 2050000,
    "gross_margin_pct": 0.21,
    "duration_months": 6,
    "order_intake_date": "2026-05",
    "promised_delivery_date": "2027-03",
    "priority": 2,
    "status": "backlog"
  }
]

export const DEFAULT_INPUTS = {
  "delay_shock_months": 0,
  "discount_rate": 0.1,
  "revenue_realization": 0.85,
  "horizon_months": 18,
  "anchor_month": "2026-01",
  "delivery_teams": 4,
  "baseline_teams": 3,
  "order_intake_growth": 0.12,
  "cost_per_team": 1000000,
  "ramp_cost_per_team": 200000,
  "fixed_cost_base_monthly": 150000,
  "run_stress": false
}

export const PRESETS = [
  {
    "id": "manufacturer",
    "label": "Manufacturer",
    "description": "Engineered-to-order shop, ~$29M book. Fund the 4th delivery crew?",
    "backlog": [
      {
        "id": "ORD-2401",
        "name": "Offshore module skid",
        "customer": "Maasvlakte Terminals",
        "market_segment": "Oil & Gas",
        "contract_value": 6400000,
        "gross_margin_pct": 0.18,
        "duration_months": 8,
        "order_intake_date": "2026-01",
        "promised_delivery_date": "2026-11",
        "priority": 1,
        "status": "in_progress"
      },
      {
        "id": "ORD-2402",
        "name": "Refinery heat exchanger",
        "customer": "Maasvlakte Terminals",
        "market_segment": "Petrochemical",
        "contract_value": 3100000,
        "gross_margin_pct": 0.22,
        "duration_months": 7,
        "order_intake_date": "2026-01",
        "promised_delivery_date": "2026-09",
        "priority": 1,
        "status": "in_progress"
      },
      {
        "id": "ORD-2403",
        "name": "Cryogenic storage tank",
        "customer": "Veridian Chemicals",
        "market_segment": "Oil & Gas",
        "contract_value": 3500000,
        "gross_margin_pct": 0.19,
        "duration_months": 7,
        "order_intake_date": "2026-02",
        "promised_delivery_date": "2026-12",
        "priority": 1,
        "status": "backlog"
      },
      {
        "id": "ORD-2404",
        "name": "Pressure vessel array",
        "customer": "Caspian Energy Group",
        "market_segment": "Petrochemical",
        "contract_value": 2300000,
        "gross_margin_pct": 0.21,
        "duration_months": 6,
        "order_intake_date": "2026-01",
        "promised_delivery_date": "2026-11",
        "priority": 2,
        "status": "in_progress"
      },
      {
        "id": "ORD-2405",
        "name": "Modular substation",
        "customer": "Caspian Energy Group",
        "market_segment": "Power Generation",
        "contract_value": 2650000,
        "gross_margin_pct": 0.2,
        "duration_months": 6,
        "order_intake_date": "2026-03",
        "promised_delivery_date": "2027-01",
        "priority": 2,
        "status": "backlog"
      },
      {
        "id": "ORD-2406",
        "name": "Turbine enclosure",
        "customer": "Alpine Process Tech",
        "market_segment": "Power Generation",
        "contract_value": 1500000,
        "gross_margin_pct": 0.24,
        "duration_months": 5,
        "order_intake_date": "2026-02",
        "promised_delivery_date": "2026-12",
        "priority": 2,
        "status": "backlog"
      },
      {
        "id": "ORD-2407",
        "name": "Marine propulsion frame",
        "customer": "Adriatic Offshore",
        "market_segment": "Marine",
        "contract_value": 1050000,
        "gross_margin_pct": 0.27,
        "duration_months": 4,
        "order_intake_date": "2026-01",
        "promised_delivery_date": "2026-10",
        "priority": 2,
        "status": "in_progress"
      },
      {
        "id": "ORD-2408",
        "name": "Flare stack package",
        "customer": "Donau Industrial",
        "market_segment": "Oil & Gas",
        "contract_value": 1200000,
        "gross_margin_pct": 0.26,
        "duration_months": 4,
        "order_intake_date": "2026-03",
        "promised_delivery_date": "2027-01",
        "priority": 3,
        "status": "backlog"
      },
      {
        "id": "ORD-2409",
        "name": "Reactor internals",
        "customer": "Caspian Energy Group",
        "market_segment": "Petrochemical",
        "contract_value": 4700000,
        "gross_margin_pct": 0.17,
        "duration_months": 8,
        "order_intake_date": "2026-04",
        "promised_delivery_date": "2027-05",
        "priority": 1,
        "status": "backlog"
      },
      {
        "id": "ORD-2410",
        "name": "Pipe rack & valve skid",
        "customer": "Adriatic Offshore",
        "market_segment": "Oil & Gas",
        "contract_value": 780000,
        "gross_margin_pct": 0.3,
        "duration_months": 3,
        "order_intake_date": "2026-02",
        "promised_delivery_date": "2026-11",
        "priority": 3,
        "status": "backlog"
      },
      {
        "id": "ORD-2411",
        "name": "Heat recovery unit",
        "customer": "Baltic Power Systems",
        "market_segment": "Power Generation",
        "contract_value": 2050000,
        "gross_margin_pct": 0.21,
        "duration_months": 6,
        "order_intake_date": "2026-05",
        "promised_delivery_date": "2027-03",
        "priority": 2,
        "status": "backlog"
      }
    ],
    "inputs": {
      "delay_shock_months": 0,
      "discount_rate": 0.1,
      "revenue_realization": 0.85,
      "horizon_months": 18,
      "anchor_month": "2026-01",
      "delivery_teams": 4,
      "baseline_teams": 3,
      "order_intake_growth": 0.12,
      "cost_per_team": 1000000,
      "ramp_cost_per_team": 200000,
      "fixed_cost_base_monthly": 150000,
      "run_stress": false
    },
    "result": {
      "timeline": [
        {
          "month": "2026-01",
          "realized": 241428.57,
          "at_risk": 0.0,
          "backlog_value": 29230000.0,
          "active_slots": 2,
          "capacity_slots": 4,
          "operating_profit": 91428.57,
          "fixed_cost_monthly": 150000.0,
          "coverage_months": 18.0
        },
        {
          "month": "2026-02",
          "realized": 336428.57,
          "at_risk": 0.0,
          "backlog_value": 27987142.86,
          "active_slots": 3,
          "capacity_slots": 4,
          "operating_profit": 186428.57,
          "fixed_cost_monthly": 150000.0,
          "coverage_months": 17.2
        },
        {
          "month": "2026-03",
          "realized": 336428.57,
          "at_risk": 0.0,
          "backlog_value": 26244285.71,
          "active_slots": 3,
          "capacity_slots": 4,
          "operating_profit": 186428.57,
          "fixed_cost_monthly": 150000.0,
          "coverage_months": 16.2
        },
        {
          "month": "2026-04",
          "realized": 436303.57,
          "at_risk": 0.0,
          "backlog_value": 24501428.57,
          "active_slots": 4,
          "capacity_slots": 4,
          "operating_profit": 286303.57,
          "fixed_cost_monthly": 150000.0,
          "coverage_months": 15.1
        },
        {
          "month": "2026-05",
          "realized": 436303.57,
          "at_risk": 0.0,
          "backlog_value": 22171071.43,
          "active_slots": 4,
          "capacity_slots": 4,
          "operating_profit": 286303.57,
          "fixed_cost_monthly": 150000.0,
          "coverage_months": 13.7
        },
        {
          "month": "2026-06",
          "realized": 436303.57,
          "at_risk": 0.0,
          "backlog_value": 19840714.29,
          "active_slots": 4,
          "capacity_slots": 4,
          "operating_profit": 286303.57,
          "fixed_cost_monthly": 150000.0,
          "coverage_months": 12.2
        },
        {
          "month": "2026-07",
          "realized": 436303.57,
          "at_risk": 0.0,
          "backlog_value": 17510357.14,
          "active_slots": 4,
          "capacity_slots": 4,
          "operating_profit": 286303.57,
          "fixed_cost_monthly": 150000.0,
          "coverage_months": 10.8
        },
        {
          "month": "2026-08",
          "realized": 409750.0,
          "at_risk": 0.0,
          "backlog_value": 15180000.0,
          "active_slots": 4,
          "capacity_slots": 4,
          "operating_profit": 259750.0,
          "fixed_cost_monthly": 150000.0,
          "coverage_months": 9.3
        },
        {
          "month": "2026-09",
          "realized": 323250.0,
          "at_risk": 0.0,
          "backlog_value": 13030000.0,
          "active_slots": 4,
          "capacity_slots": 4,
          "operating_profit": 173250.0,
          "fixed_cost_monthly": 150000.0,
          "coverage_months": 8.0
        },
        {
          "month": "2026-10",
          "realized": 252375.0,
          "at_risk": 70875.0,
          "backlog_value": 11496666.67,
          "active_slots": 4,
          "capacity_slots": 4,
          "operating_profit": 162618.75,
          "fixed_cost_monthly": 150000.0,
          "coverage_months": 7.1
        },
        {
          "month": "2026-11",
          "realized": 171875.0,
          "at_risk": 151375.0,
          "backlog_value": 9963333.33,
          "active_slots": 4,
          "capacity_slots": 4,
          "operating_profit": 150543.75,
          "fixed_cost_monthly": 150000.0,
          "coverage_months": 6.1
        },
        {
          "month": "2026-12",
          "realized": 160083.33,
          "at_risk": 152500.0,
          "backlog_value": 8430000.0,
          "active_slots": 4,
          "capacity_slots": 4,
          "operating_profit": 139708.33,
          "fixed_cost_monthly": 150000.0,
          "coverage_months": 5.2
        },
        {
          "month": "2027-01",
          "realized": 71750.0,
          "at_risk": 240833.33,
          "backlog_value": 6963333.33,
          "active_slots": 4,
          "capacity_slots": 4,
          "operating_profit": 126458.33,
          "fixed_cost_monthly": 150000.0,
          "coverage_months": 4.3
        },
        {
          "month": "2027-02",
          "realized": 71750.0,
          "at_risk": 246833.33,
          "backlog_value": 5496666.67,
          "active_slots": 4,
          "capacity_slots": 4,
          "operating_profit": 131558.33,
          "fixed_cost_monthly": 150000.0,
          "coverage_months": 3.4
        },
        {
          "month": "2027-03",
          "realized": 0.0,
          "at_risk": 316083.33,
          "backlog_value": 4070000.0,
          "active_slots": 4,
          "capacity_slots": 4,
          "operating_profit": 118670.83,
          "fixed_cost_monthly": 150000.0,
          "coverage_months": 2.5
        },
        {
          "month": "2027-04",
          "realized": 0.0,
          "at_risk": 316083.33,
          "backlog_value": 2726666.67,
          "active_slots": 4,
          "capacity_slots": 4,
          "operating_profit": 118670.83,
          "fixed_cost_monthly": 150000.0,
          "coverage_months": 1.7
        },
        {
          "month": "2027-05",
          "realized": 0.0,
          "at_risk": 238083.33,
          "backlog_value": 1383333.33,
          "active_slots": 3,
          "capacity_slots": 4,
          "operating_profit": 52370.83,
          "fixed_cost_monthly": 150000.0,
          "coverage_months": 0.9
        },
        {
          "month": "2027-06",
          "realized": 0.0,
          "at_risk": 78000.0,
          "backlog_value": 300000.0,
          "active_slots": 1,
          "capacity_slots": 4,
          "operating_profit": -83700.0,
          "fixed_cost_monthly": 150000.0,
          "coverage_months": 0.2
        }
      ],
      "capacity_gap": [
        {
          "month": "2026-01",
          "demand_slots": 0,
          "available_slots": 4,
          "gap": 0
        },
        {
          "month": "2026-02",
          "demand_slots": 1,
          "available_slots": 4,
          "gap": 0
        },
        {
          "month": "2026-03",
          "demand_slots": 2,
          "available_slots": 4,
          "gap": 0
        },
        {
          "month": "2026-04",
          "demand_slots": 2,
          "available_slots": 4,
          "gap": 0
        },
        {
          "month": "2026-05",
          "demand_slots": 4,
          "available_slots": 4,
          "gap": 0
        },
        {
          "month": "2026-06",
          "demand_slots": 5,
          "available_slots": 4,
          "gap": 1
        },
        {
          "month": "2026-07",
          "demand_slots": 7,
          "available_slots": 4,
          "gap": 3
        },
        {
          "month": "2026-08",
          "demand_slots": 8,
          "available_slots": 4,
          "gap": 4
        },
        {
          "month": "2026-09",
          "demand_slots": 10,
          "available_slots": 4,
          "gap": 6
        },
        {
          "month": "2026-10",
          "demand_slots": 9,
          "available_slots": 4,
          "gap": 5
        },
        {
          "month": "2026-11",
          "demand_slots": 6,
          "available_slots": 4,
          "gap": 2
        },
        {
          "month": "2026-12",
          "demand_slots": 4,
          "available_slots": 4,
          "gap": 0
        },
        {
          "month": "2027-01",
          "demand_slots": 2,
          "available_slots": 4,
          "gap": 0
        },
        {
          "month": "2027-02",
          "demand_slots": 2,
          "available_slots": 4,
          "gap": 0
        },
        {
          "month": "2027-03",
          "demand_slots": 1,
          "available_slots": 4,
          "gap": 0
        },
        {
          "month": "2027-04",
          "demand_slots": 1,
          "available_slots": 4,
          "gap": 0
        },
        {
          "month": "2027-05",
          "demand_slots": 0,
          "available_slots": 4,
          "gap": 0
        },
        {
          "month": "2027-06",
          "demand_slots": 0,
          "available_slots": 4,
          "gap": 0
        }
      ],
      "headcount_roi": {
        "added_teams": 1,
        "baseline_teams": 3,
        "incremental_pv_margin": 1895956.64,
        "quality_pv_gain": 777400.59,
        "throughput_pv_gain": 1118556.05,
        "initial_cost": 200000.0,
        "annual_cost": 1000000.0,
        "total_cost": 1592164.97,
        "cost_valid": true,
        "raw_multiple": 1.191,
        "roi_pct": 19.1,
        "npv": 303791.66,
        "payback_months": 6,
        "discount_rate": 0.1,
        "revenue_realization": 0.85
      },
      "sensitivity": [
        {
          "factor": "Cost per team",
          "low": 1.4,
          "high": 44.3,
          "swing": 42.9
        },
        {
          "factor": "Revenue realization",
          "low": 9.3,
          "high": 28.9,
          "swing": 19.6
        },
        {
          "factor": "Delivery teams",
          "low": 1.3,
          "high": 19.1,
          "swing": 17.8
        },
        {
          "factor": "Order-intake growth",
          "low": 10.8,
          "high": 27.3,
          "swing": 16.5
        },
        {
          "factor": "Delay shock",
          "low": 19.1,
          "high": 22.2,
          "swing": 3.1
        }
      ],
      "summary": {
        "company": "Meridian Technologies",
        "backlog_projects": 11,
        "backlog_value": 29230000.0,
        "horizon_months": 18,
        "realized_total": 4120333.32,
        "at_risk_total": 1810666.65,
        "at_risk_share_pct": 30.5,
        "months_capacity_short": 6,
        "backlog_cleared_pct": 99.0,
        "operating_profit_total": 2959399.97,
        "op_margin_pct": 52.3,
        "coverage_months_now": 18.0,
        "coverage_warning_month": "2026-12",
        "fixed_cost_base_monthly": 150000.0
      },
      "stress_timeline": null,
      "stress_comparison": null
    }
  },
  {
    "id": "services",
    "label": "Services Firm",
    "description": "Consultancy / agency, ~$1.4M of engagements growing 16%. Add a 3rd delivery pod?",
    "backlog": [
      {
        "id": "ENG-201",
        "name": "Brand & web rebuild",
        "contract_value": 320000,
        "gross_margin_pct": 0.45,
        "duration_months": 4,
        "order_intake_date": "2026-01",
        "promised_delivery_date": "2026-06",
        "priority": 1
      },
      {
        "id": "ENG-202",
        "name": "ERP rollout advisory",
        "contract_value": 280000,
        "gross_margin_pct": 0.4,
        "duration_months": 5,
        "order_intake_date": "2026-01",
        "promised_delivery_date": "2026-07",
        "priority": 1
      },
      {
        "id": "ENG-203",
        "name": "Data platform build",
        "contract_value": 240000,
        "gross_margin_pct": 0.42,
        "duration_months": 4,
        "order_intake_date": "2026-02",
        "promised_delivery_date": "2026-08",
        "priority": 2
      },
      {
        "id": "ENG-204",
        "name": "Mobile app MVP",
        "contract_value": 180000,
        "gross_margin_pct": 0.38,
        "duration_months": 4,
        "order_intake_date": "2026-03",
        "promised_delivery_date": "2026-09",
        "priority": 1
      },
      {
        "id": "ENG-205",
        "name": "Marketing retainer H1",
        "contract_value": 160000,
        "gross_margin_pct": 0.5,
        "duration_months": 6,
        "order_intake_date": "2026-01",
        "promised_delivery_date": "2026-08",
        "priority": 2
      },
      {
        "id": "ENG-206",
        "name": "Security audit",
        "contract_value": 95000,
        "gross_margin_pct": 0.48,
        "duration_months": 2,
        "order_intake_date": "2026-02",
        "promised_delivery_date": "2026-05",
        "priority": 2
      },
      {
        "id": "ENG-207",
        "name": "Analytics dashboards",
        "contract_value": 85000,
        "gross_margin_pct": 0.46,
        "duration_months": 2,
        "order_intake_date": "2026-03",
        "promised_delivery_date": "2026-06",
        "priority": 3
      },
      {
        "id": "ENG-208",
        "name": "Change-mgmt workshops",
        "contract_value": 60000,
        "gross_margin_pct": 0.52,
        "duration_months": 2,
        "order_intake_date": "2026-04",
        "promised_delivery_date": "2026-07",
        "priority": 3
      }
    ],
    "inputs": {
      "delay_shock_months": 0,
      "discount_rate": 0.1,
      "revenue_realization": 0.85,
      "horizon_months": 18,
      "anchor_month": "2026-01",
      "delivery_teams": 3,
      "baseline_teams": 2,
      "order_intake_growth": 0.16,
      "cost_per_team": 155000,
      "ramp_cost_per_team": 25000,
      "fixed_cost_base_monthly": 25000,
      "run_stress": false
    },
    "result": {
      "timeline": [
        {
          "month": "2026-01",
          "realized": 58400.0,
          "at_risk": 0.0,
          "backlog_value": 1420000.0,
          "active_slots": 2,
          "capacity_slots": 3,
          "operating_profit": 33400.0,
          "fixed_cost_monthly": 25000.0,
          "coverage_months": 12.0
        },
        {
          "month": "2026-02",
          "realized": 58400.0,
          "at_risk": 0.0,
          "backlog_value": 1284000.0,
          "active_slots": 2,
          "capacity_slots": 3,
          "operating_profit": 33400.0,
          "fixed_cost_monthly": 25000.0,
          "coverage_months": 10.9
        },
        {
          "month": "2026-03",
          "realized": 75500.0,
          "at_risk": 0.0,
          "backlog_value": 1148000.0,
          "active_slots": 3,
          "capacity_slots": 3,
          "operating_profit": 50500.0,
          "fixed_cost_monthly": 25000.0,
          "coverage_months": 9.7
        },
        {
          "month": "2026-04",
          "realized": 75500.0,
          "at_risk": 0.0,
          "backlog_value": 967000.0,
          "active_slots": 3,
          "capacity_slots": 3,
          "operating_profit": 50500.0,
          "fixed_cost_monthly": 25000.0,
          "coverage_months": 8.2
        },
        {
          "month": "2026-05",
          "realized": 39500.0,
          "at_risk": 22800.0,
          "backlog_value": 786000.0,
          "active_slots": 3,
          "capacity_slots": 3,
          "operating_profit": 33880.0,
          "fixed_cost_monthly": 25000.0,
          "coverage_months": 6.6
        },
        {
          "month": "2026-06",
          "realized": 42300.0,
          "at_risk": 22800.0,
          "backlog_value": 637500.0,
          "active_slots": 3,
          "capacity_slots": 3,
          "operating_profit": 36680.0,
          "fixed_cost_monthly": 25000.0,
          "coverage_months": 5.4
        },
        {
          "month": "2026-07",
          "realized": 38533.33,
          "at_risk": 19550.0,
          "backlog_value": 485000.0,
          "active_slots": 3,
          "capacity_slots": 3,
          "operating_profit": 30150.83,
          "fixed_cost_monthly": 25000.0,
          "coverage_months": 4.1
        },
        {
          "month": "2026-08",
          "realized": 0.0,
          "at_risk": 58083.33,
          "backlog_value": 355833.33,
          "active_slots": 3,
          "capacity_slots": 3,
          "operating_profit": 24370.83,
          "fixed_cost_monthly": 25000.0,
          "coverage_months": 3.0
        },
        {
          "month": "2026-09",
          "realized": 0.0,
          "at_risk": 54133.33,
          "backlog_value": 226666.67,
          "active_slots": 3,
          "capacity_slots": 3,
          "operating_profit": 21013.33,
          "fixed_cost_monthly": 25000.0,
          "coverage_months": 1.9
        },
        {
          "month": "2026-10",
          "realized": 0.0,
          "at_risk": 28933.33,
          "backlog_value": 110000.0,
          "active_slots": 2,
          "capacity_slots": 3,
          "operating_profit": -406.67,
          "fixed_cost_monthly": 25000.0,
          "coverage_months": 0.9
        },
        {
          "month": "2026-11",
          "realized": 0.0,
          "at_risk": 13333.33,
          "backlog_value": 53333.33,
          "active_slots": 1,
          "capacity_slots": 3,
          "operating_profit": -13666.67,
          "fixed_cost_monthly": 25000.0,
          "coverage_months": 0.5
        },
        {
          "month": "2026-12",
          "realized": 0.0,
          "at_risk": 13333.33,
          "backlog_value": 26666.67,
          "active_slots": 1,
          "capacity_slots": 3,
          "operating_profit": -13666.67,
          "fixed_cost_monthly": 25000.0,
          "coverage_months": 0.2
        },
        {
          "month": "2027-01",
          "realized": 0.0,
          "at_risk": 0.0,
          "backlog_value": 0.0,
          "active_slots": 0,
          "capacity_slots": 3,
          "operating_profit": -25000.0,
          "fixed_cost_monthly": 25000.0,
          "coverage_months": 0.0
        },
        {
          "month": "2027-02",
          "realized": 0.0,
          "at_risk": 0.0,
          "backlog_value": 0.0,
          "active_slots": 0,
          "capacity_slots": 3,
          "operating_profit": -25000.0,
          "fixed_cost_monthly": 25000.0,
          "coverage_months": 0.0
        },
        {
          "month": "2027-03",
          "realized": 0.0,
          "at_risk": 0.0,
          "backlog_value": 0.0,
          "active_slots": 0,
          "capacity_slots": 3,
          "operating_profit": -25000.0,
          "fixed_cost_monthly": 25000.0,
          "coverage_months": 0.0
        },
        {
          "month": "2027-04",
          "realized": 0.0,
          "at_risk": 0.0,
          "backlog_value": 0.0,
          "active_slots": 0,
          "capacity_slots": 3,
          "operating_profit": -25000.0,
          "fixed_cost_monthly": 25000.0,
          "coverage_months": 0.0
        },
        {
          "month": "2027-05",
          "realized": 0.0,
          "at_risk": 0.0,
          "backlog_value": 0.0,
          "active_slots": 0,
          "capacity_slots": 3,
          "operating_profit": -25000.0,
          "fixed_cost_monthly": 25000.0,
          "coverage_months": 0.0
        },
        {
          "month": "2027-06",
          "realized": 0.0,
          "at_risk": 0.0,
          "backlog_value": 0.0,
          "active_slots": 0,
          "capacity_slots": 3,
          "operating_profit": -25000.0,
          "fixed_cost_monthly": 25000.0,
          "coverage_months": 0.0
        }
      ],
      "capacity_gap": [
        {
          "month": "2026-01",
          "demand_slots": 0,
          "available_slots": 3,
          "gap": 0
        },
        {
          "month": "2026-02",
          "demand_slots": 3,
          "available_slots": 3,
          "gap": 0
        },
        {
          "month": "2026-03",
          "demand_slots": 4,
          "available_slots": 3,
          "gap": 1
        },
        {
          "month": "2026-04",
          "demand_slots": 6,
          "available_slots": 3,
          "gap": 3
        },
        {
          "month": "2026-05",
          "demand_slots": 7,
          "available_slots": 3,
          "gap": 4
        },
        {
          "month": "2026-06",
          "demand_slots": 5,
          "available_slots": 3,
          "gap": 2
        },
        {
          "month": "2026-07",
          "demand_slots": 3,
          "available_slots": 3,
          "gap": 0
        },
        {
          "month": "2026-08",
          "demand_slots": 1,
          "available_slots": 3,
          "gap": 0
        },
        {
          "month": "2026-09",
          "demand_slots": 0,
          "available_slots": 3,
          "gap": 0
        },
        {
          "month": "2026-10",
          "demand_slots": 0,
          "available_slots": 3,
          "gap": 0
        },
        {
          "month": "2026-11",
          "demand_slots": 0,
          "available_slots": 3,
          "gap": 0
        },
        {
          "month": "2026-12",
          "demand_slots": 0,
          "available_slots": 3,
          "gap": 0
        },
        {
          "month": "2027-01",
          "demand_slots": 0,
          "available_slots": 3,
          "gap": 0
        },
        {
          "month": "2027-02",
          "demand_slots": 0,
          "available_slots": 3,
          "gap": 0
        },
        {
          "month": "2027-03",
          "demand_slots": 0,
          "available_slots": 3,
          "gap": 0
        },
        {
          "month": "2027-04",
          "demand_slots": 0,
          "available_slots": 3,
          "gap": 0
        },
        {
          "month": "2027-05",
          "demand_slots": 0,
          "available_slots": 3,
          "gap": 0
        },
        {
          "month": "2027-06",
          "demand_slots": 0,
          "available_slots": 3,
          "gap": 0
        }
      ],
      "headcount_roi": {
        "added_teams": 1,
        "baseline_teams": 2,
        "incremental_pv_margin": 303886.61,
        "quality_pv_gain": 14966.34,
        "throughput_pv_gain": 288920.27,
        "initial_cost": 25000.0,
        "annual_cost": 155000.0,
        "total_cost": 240785.57,
        "cost_valid": true,
        "raw_multiple": 1.262,
        "roi_pct": 26.2,
        "npv": 63101.04,
        "payback_months": 3,
        "discount_rate": 0.1,
        "revenue_realization": 0.85
      },
      "sensitivity": [
        {
          "factor": "Cost per team",
          "low": 7.0,
          "high": 53.8,
          "swing": 46.8
        },
        {
          "factor": "Revenue realization",
          "low": 14.4,
          "high": 38.0,
          "swing": 23.6
        },
        {
          "factor": "Order-intake growth",
          "low": 13.6,
          "high": 32.5,
          "swing": 18.9
        },
        {
          "factor": "Delivery teams",
          "low": 26.2,
          "high": 27.6,
          "swing": 1.4
        },
        {
          "factor": "Delay shock",
          "low": 25.7,
          "high": 26.2,
          "swing": 0.5
        }
      ],
      "summary": {
        "company": "Meridian Technologies",
        "backlog_projects": 8,
        "backlog_value": 1420000.0,
        "horizon_months": 18,
        "realized_total": 388133.33,
        "at_risk_total": 232966.65,
        "at_risk_share_pct": 37.5,
        "months_capacity_short": 4,
        "backlog_cleared_pct": 100.0,
        "operating_profit_total": 136154.98,
        "op_margin_pct": 23.2,
        "coverage_months_now": 12.0,
        "coverage_warning_month": "2026-06",
        "fixed_cost_base_monthly": 25000.0
      },
      "stress_timeline": null,
      "stress_comparison": null
    }
  },
  {
    "id": "small_shop",
    "label": "Small Shop",
    "description": "A small fabricator, ~$290K book. Does a 2nd person pay yet at this scale?",
    "backlog": [
      {
        "id": "JOB-101",
        "name": "Custom stair & railing",
        "contract_value": 88000,
        "gross_margin_pct": 0.28,
        "duration_months": 3,
        "order_intake_date": "2026-01",
        "promised_delivery_date": "2026-05",
        "priority": 1
      },
      {
        "id": "JOB-102",
        "name": "Retail fit-out millwork",
        "contract_value": 72000,
        "gross_margin_pct": 0.3,
        "duration_months": 3,
        "order_intake_date": "2026-01",
        "promised_delivery_date": "2026-05",
        "priority": 1
      },
      {
        "id": "JOB-103",
        "name": "Mezzanine platform",
        "contract_value": 52000,
        "gross_margin_pct": 0.26,
        "duration_months": 2,
        "order_intake_date": "2026-02",
        "promised_delivery_date": "2026-06",
        "priority": 2
      },
      {
        "id": "JOB-104",
        "name": "Equipment guarding",
        "contract_value": 34000,
        "gross_margin_pct": 0.34,
        "duration_months": 2,
        "order_intake_date": "2026-02",
        "promised_delivery_date": "2026-05",
        "priority": 2
      },
      {
        "id": "JOB-105",
        "name": "Trailer chassis repair",
        "contract_value": 26000,
        "gross_margin_pct": 0.32,
        "duration_months": 2,
        "order_intake_date": "2026-03",
        "promised_delivery_date": "2026-06",
        "priority": 3
      },
      {
        "id": "JOB-106",
        "name": "Conveyor brackets batch",
        "contract_value": 18000,
        "gross_margin_pct": 0.38,
        "duration_months": 1,
        "order_intake_date": "2026-03",
        "promised_delivery_date": "2026-05",
        "priority": 3
      }
    ],
    "inputs": {
      "delay_shock_months": 0,
      "discount_rate": 0.1,
      "revenue_realization": 0.85,
      "horizon_months": 18,
      "anchor_month": "2026-01",
      "delivery_teams": 2,
      "baseline_teams": 1,
      "order_intake_growth": 0.12,
      "cost_per_team": 80000,
      "ramp_cost_per_team": 8000,
      "fixed_cost_base_monthly": 6500,
      "run_stress": false
    },
    "result": {
      "timeline": [
        {
          "month": "2026-01",
          "realized": 15413.33,
          "at_risk": 0.0,
          "backlog_value": 290000.0,
          "active_slots": 2,
          "capacity_slots": 2,
          "operating_profit": 8913.33,
          "fixed_cost_monthly": 6500.0,
          "coverage_months": 7.0
        },
        {
          "month": "2026-02",
          "realized": 15413.33,
          "at_risk": 0.0,
          "backlog_value": 236666.67,
          "active_slots": 2,
          "capacity_slots": 2,
          "operating_profit": 8913.33,
          "fixed_cost_monthly": 6500.0,
          "coverage_months": 5.7
        },
        {
          "month": "2026-03",
          "realized": 15413.33,
          "at_risk": 0.0,
          "backlog_value": 183333.33,
          "active_slots": 2,
          "capacity_slots": 2,
          "operating_profit": 8913.33,
          "fixed_cost_monthly": 6500.0,
          "coverage_months": 4.4
        },
        {
          "month": "2026-04",
          "realized": 12540.0,
          "at_risk": 0.0,
          "backlog_value": 130000.0,
          "active_slots": 2,
          "capacity_slots": 2,
          "operating_profit": 6040.0,
          "fixed_cost_monthly": 6500.0,
          "coverage_months": 3.1
        },
        {
          "month": "2026-05",
          "realized": 6760.0,
          "at_risk": 5780.0,
          "backlog_value": 87000.0,
          "active_slots": 2,
          "capacity_slots": 2,
          "operating_profit": 5173.0,
          "fixed_cost_monthly": 6500.0,
          "coverage_months": 2.1
        },
        {
          "month": "2026-06",
          "realized": 0.0,
          "at_risk": 11000.0,
          "backlog_value": 44000.0,
          "active_slots": 2,
          "capacity_slots": 2,
          "operating_profit": 2850.0,
          "fixed_cost_monthly": 6500.0,
          "coverage_months": 1.1
        },
        {
          "month": "2026-07",
          "realized": 0.0,
          "at_risk": 4160.0,
          "backlog_value": 13000.0,
          "active_slots": 1,
          "capacity_slots": 2,
          "operating_profit": -2964.0,
          "fixed_cost_monthly": 6500.0,
          "coverage_months": 0.3
        },
        {
          "month": "2026-08",
          "realized": 0.0,
          "at_risk": 0.0,
          "backlog_value": 0.0,
          "active_slots": 0,
          "capacity_slots": 2,
          "operating_profit": -6500.0,
          "fixed_cost_monthly": 6500.0,
          "coverage_months": 0.0
        },
        {
          "month": "2026-09",
          "realized": 0.0,
          "at_risk": 0.0,
          "backlog_value": 0.0,
          "active_slots": 0,
          "capacity_slots": 2,
          "operating_profit": -6500.0,
          "fixed_cost_monthly": 6500.0,
          "coverage_months": 0.0
        },
        {
          "month": "2026-10",
          "realized": 0.0,
          "at_risk": 0.0,
          "backlog_value": 0.0,
          "active_slots": 0,
          "capacity_slots": 2,
          "operating_profit": -6500.0,
          "fixed_cost_monthly": 6500.0,
          "coverage_months": 0.0
        },
        {
          "month": "2026-11",
          "realized": 0.0,
          "at_risk": 0.0,
          "backlog_value": 0.0,
          "active_slots": 0,
          "capacity_slots": 2,
          "operating_profit": -6500.0,
          "fixed_cost_monthly": 6500.0,
          "coverage_months": 0.0
        },
        {
          "month": "2026-12",
          "realized": 0.0,
          "at_risk": 0.0,
          "backlog_value": 0.0,
          "active_slots": 0,
          "capacity_slots": 2,
          "operating_profit": -6500.0,
          "fixed_cost_monthly": 6500.0,
          "coverage_months": 0.0
        },
        {
          "month": "2027-01",
          "realized": 0.0,
          "at_risk": 0.0,
          "backlog_value": 0.0,
          "active_slots": 0,
          "capacity_slots": 2,
          "operating_profit": -6500.0,
          "fixed_cost_monthly": 6500.0,
          "coverage_months": 0.0
        },
        {
          "month": "2027-02",
          "realized": 0.0,
          "at_risk": 0.0,
          "backlog_value": 0.0,
          "active_slots": 0,
          "capacity_slots": 2,
          "operating_profit": -6500.0,
          "fixed_cost_monthly": 6500.0,
          "coverage_months": 0.0
        },
        {
          "month": "2027-03",
          "realized": 0.0,
          "at_risk": 0.0,
          "backlog_value": 0.0,
          "active_slots": 0,
          "capacity_slots": 2,
          "operating_profit": -6500.0,
          "fixed_cost_monthly": 6500.0,
          "coverage_months": 0.0
        },
        {
          "month": "2027-04",
          "realized": 0.0,
          "at_risk": 0.0,
          "backlog_value": 0.0,
          "active_slots": 0,
          "capacity_slots": 2,
          "operating_profit": -6500.0,
          "fixed_cost_monthly": 6500.0,
          "coverage_months": 0.0
        },
        {
          "month": "2027-05",
          "realized": 0.0,
          "at_risk": 0.0,
          "backlog_value": 0.0,
          "active_slots": 0,
          "capacity_slots": 2,
          "operating_profit": -6500.0,
          "fixed_cost_monthly": 6500.0,
          "coverage_months": 0.0
        },
        {
          "month": "2027-06",
          "realized": 0.0,
          "at_risk": 0.0,
          "backlog_value": 0.0,
          "active_slots": 0,
          "capacity_slots": 2,
          "operating_profit": -6500.0,
          "fixed_cost_monthly": 6500.0,
          "coverage_months": 0.0
        }
      ],
      "capacity_gap": [
        {
          "month": "2026-01",
          "demand_slots": 0,
          "available_slots": 2,
          "gap": 0
        },
        {
          "month": "2026-02",
          "demand_slots": 2,
          "available_slots": 2,
          "gap": 0
        },
        {
          "month": "2026-03",
          "demand_slots": 3,
          "available_slots": 2,
          "gap": 1
        },
        {
          "month": "2026-04",
          "demand_slots": 6,
          "available_slots": 2,
          "gap": 4
        },
        {
          "month": "2026-05",
          "demand_slots": 2,
          "available_slots": 2,
          "gap": 0
        },
        {
          "month": "2026-06",
          "demand_slots": 0,
          "available_slots": 2,
          "gap": 0
        },
        {
          "month": "2026-07",
          "demand_slots": 0,
          "available_slots": 2,
          "gap": 0
        },
        {
          "month": "2026-08",
          "demand_slots": 0,
          "available_slots": 2,
          "gap": 0
        },
        {
          "month": "2026-09",
          "demand_slots": 0,
          "available_slots": 2,
          "gap": 0
        },
        {
          "month": "2026-10",
          "demand_slots": 0,
          "available_slots": 2,
          "gap": 0
        },
        {
          "month": "2026-11",
          "demand_slots": 0,
          "available_slots": 2,
          "gap": 0
        },
        {
          "month": "2026-12",
          "demand_slots": 0,
          "available_slots": 2,
          "gap": 0
        },
        {
          "month": "2027-01",
          "demand_slots": 0,
          "available_slots": 2,
          "gap": 0
        },
        {
          "month": "2027-02",
          "demand_slots": 0,
          "available_slots": 2,
          "gap": 0
        },
        {
          "month": "2027-03",
          "demand_slots": 0,
          "available_slots": 2,
          "gap": 0
        },
        {
          "month": "2027-04",
          "demand_slots": 0,
          "available_slots": 2,
          "gap": 0
        },
        {
          "month": "2027-05",
          "demand_slots": 0,
          "available_slots": 2,
          "gap": 0
        },
        {
          "month": "2027-06",
          "demand_slots": 0,
          "available_slots": 2,
          "gap": 0
        }
      ],
      "headcount_roi": {
        "added_teams": 1,
        "baseline_teams": 1,
        "incremental_pv_margin": 86894.37,
        "quality_pv_gain": 6600.55,
        "throughput_pv_gain": 80293.82,
        "initial_cost": 8000.0,
        "annual_cost": 80000.0,
        "total_cost": 119373.2,
        "cost_valid": true,
        "raw_multiple": 0.728,
        "roi_pct": -27.2,
        "npv": -32478.83,
        "payback_months": null,
        "discount_rate": 0.1,
        "revenue_realization": 0.85
      },
      "sensitivity": [
        {
          "factor": "Cost per team",
          "low": -38.7,
          "high": -10.5,
          "swing": 28.2
        },
        {
          "factor": "Order-intake growth",
          "low": -35.1,
          "high": -19.3,
          "swing": 15.8
        },
        {
          "factor": "Revenue realization",
          "low": -32.5,
          "high": -21.9,
          "swing": 10.6
        },
        {
          "factor": "Delivery teams",
          "low": -28.5,
          "high": -27.2,
          "swing": 1.3
        },
        {
          "factor": "Delay shock",
          "low": -27.3,
          "high": -27.2,
          "swing": 0.1
        }
      ],
      "summary": {
        "company": "Meridian Technologies",
        "backlog_projects": 6,
        "backlog_value": 290000.0,
        "horizon_months": 18,
        "realized_total": 65539.99,
        "at_risk_total": 20940.0,
        "at_risk_share_pct": 24.2,
        "months_capacity_short": 2,
        "backlog_cleared_pct": 100.0,
        "operating_profit_total": -33661.01,
        "op_margin_pct": -40.4,
        "coverage_months_now": 7.0,
        "coverage_warning_month": "2026-02",
        "fixed_cost_base_monthly": 6500.0
      },
      "stress_timeline": null,
      "stress_comparison": null
    }
  },
  {
    "id": "squeeze",
    "label": "Cost Squeeze",
    "description": "The manufacturer, but $1.6M crews and a 2-month flagship slip. Still worth it?",
    "backlog": [
      {
        "id": "ORD-2401",
        "name": "Offshore module skid",
        "customer": "Maasvlakte Terminals",
        "market_segment": "Oil & Gas",
        "contract_value": 6400000,
        "gross_margin_pct": 0.18,
        "duration_months": 8,
        "order_intake_date": "2026-01",
        "promised_delivery_date": "2026-11",
        "priority": 1,
        "status": "in_progress"
      },
      {
        "id": "ORD-2402",
        "name": "Refinery heat exchanger",
        "customer": "Maasvlakte Terminals",
        "market_segment": "Petrochemical",
        "contract_value": 3100000,
        "gross_margin_pct": 0.22,
        "duration_months": 7,
        "order_intake_date": "2026-01",
        "promised_delivery_date": "2026-09",
        "priority": 1,
        "status": "in_progress"
      },
      {
        "id": "ORD-2403",
        "name": "Cryogenic storage tank",
        "customer": "Veridian Chemicals",
        "market_segment": "Oil & Gas",
        "contract_value": 3500000,
        "gross_margin_pct": 0.19,
        "duration_months": 7,
        "order_intake_date": "2026-02",
        "promised_delivery_date": "2026-12",
        "priority": 1,
        "status": "backlog"
      },
      {
        "id": "ORD-2404",
        "name": "Pressure vessel array",
        "customer": "Caspian Energy Group",
        "market_segment": "Petrochemical",
        "contract_value": 2300000,
        "gross_margin_pct": 0.21,
        "duration_months": 6,
        "order_intake_date": "2026-01",
        "promised_delivery_date": "2026-11",
        "priority": 2,
        "status": "in_progress"
      },
      {
        "id": "ORD-2405",
        "name": "Modular substation",
        "customer": "Caspian Energy Group",
        "market_segment": "Power Generation",
        "contract_value": 2650000,
        "gross_margin_pct": 0.2,
        "duration_months": 6,
        "order_intake_date": "2026-03",
        "promised_delivery_date": "2027-01",
        "priority": 2,
        "status": "backlog"
      },
      {
        "id": "ORD-2406",
        "name": "Turbine enclosure",
        "customer": "Alpine Process Tech",
        "market_segment": "Power Generation",
        "contract_value": 1500000,
        "gross_margin_pct": 0.24,
        "duration_months": 5,
        "order_intake_date": "2026-02",
        "promised_delivery_date": "2026-12",
        "priority": 2,
        "status": "backlog"
      },
      {
        "id": "ORD-2407",
        "name": "Marine propulsion frame",
        "customer": "Adriatic Offshore",
        "market_segment": "Marine",
        "contract_value": 1050000,
        "gross_margin_pct": 0.27,
        "duration_months": 4,
        "order_intake_date": "2026-01",
        "promised_delivery_date": "2026-10",
        "priority": 2,
        "status": "in_progress"
      },
      {
        "id": "ORD-2408",
        "name": "Flare stack package",
        "customer": "Donau Industrial",
        "market_segment": "Oil & Gas",
        "contract_value": 1200000,
        "gross_margin_pct": 0.26,
        "duration_months": 4,
        "order_intake_date": "2026-03",
        "promised_delivery_date": "2027-01",
        "priority": 3,
        "status": "backlog"
      },
      {
        "id": "ORD-2409",
        "name": "Reactor internals",
        "customer": "Caspian Energy Group",
        "market_segment": "Petrochemical",
        "contract_value": 4700000,
        "gross_margin_pct": 0.17,
        "duration_months": 8,
        "order_intake_date": "2026-04",
        "promised_delivery_date": "2027-05",
        "priority": 1,
        "status": "backlog"
      },
      {
        "id": "ORD-2410",
        "name": "Pipe rack & valve skid",
        "customer": "Adriatic Offshore",
        "market_segment": "Oil & Gas",
        "contract_value": 780000,
        "gross_margin_pct": 0.3,
        "duration_months": 3,
        "order_intake_date": "2026-02",
        "promised_delivery_date": "2026-11",
        "priority": 3,
        "status": "backlog"
      },
      {
        "id": "ORD-2411",
        "name": "Heat recovery unit",
        "customer": "Baltic Power Systems",
        "market_segment": "Power Generation",
        "contract_value": 2050000,
        "gross_margin_pct": 0.21,
        "duration_months": 6,
        "order_intake_date": "2026-05",
        "promised_delivery_date": "2027-03",
        "priority": 2,
        "status": "backlog"
      }
    ],
    "inputs": {
      "delay_shock_months": 2,
      "discount_rate": 0.1,
      "revenue_realization": 0.85,
      "horizon_months": 18,
      "anchor_month": "2026-01",
      "delivery_teams": 4,
      "baseline_teams": 3,
      "order_intake_growth": 0.12,
      "cost_per_team": 1600000,
      "ramp_cost_per_team": 200000,
      "fixed_cost_base_monthly": 150000,
      "run_stress": false
    },
    "result": {
      "timeline": [
        {
          "month": "2026-01",
          "realized": 212628.57,
          "at_risk": 0.0,
          "backlog_value": 29230000.0,
          "active_slots": 2,
          "capacity_slots": 4,
          "operating_profit": 62628.57,
          "fixed_cost_monthly": 150000.0,
          "coverage_months": 18.2
        },
        {
          "month": "2026-02",
          "realized": 307628.57,
          "at_risk": 0.0,
          "backlog_value": 28147142.86,
          "active_slots": 3,
          "capacity_slots": 4,
          "operating_profit": 157628.57,
          "fixed_cost_monthly": 150000.0,
          "coverage_months": 17.5
        },
        {
          "month": "2026-03",
          "realized": 307628.57,
          "at_risk": 0.0,
          "backlog_value": 26564285.71,
          "active_slots": 3,
          "capacity_slots": 4,
          "operating_profit": 157628.57,
          "fixed_cost_monthly": 150000.0,
          "coverage_months": 16.5
        },
        {
          "month": "2026-04",
          "realized": 407503.57,
          "at_risk": 0.0,
          "backlog_value": 24981428.57,
          "active_slots": 4,
          "capacity_slots": 4,
          "operating_profit": 257503.57,
          "fixed_cost_monthly": 150000.0,
          "coverage_months": 15.5
        },
        {
          "month": "2026-05",
          "realized": 407503.57,
          "at_risk": 0.0,
          "backlog_value": 22811071.43,
          "active_slots": 4,
          "capacity_slots": 4,
          "operating_profit": 257503.57,
          "fixed_cost_monthly": 150000.0,
          "coverage_months": 14.2
        },
        {
          "month": "2026-06",
          "realized": 407503.57,
          "at_risk": 0.0,
          "backlog_value": 20640714.29,
          "active_slots": 4,
          "capacity_slots": 4,
          "operating_profit": 257503.57,
          "fixed_cost_monthly": 150000.0,
          "coverage_months": 12.8
        },
        {
          "month": "2026-07",
          "realized": 407503.57,
          "at_risk": 0.0,
          "backlog_value": 18470357.14,
          "active_slots": 4,
          "capacity_slots": 4,
          "operating_profit": 257503.57,
          "fixed_cost_monthly": 150000.0,
          "coverage_months": 11.5
        },
        {
          "month": "2026-08",
          "realized": 380950.0,
          "at_risk": 0.0,
          "backlog_value": 16300000.0,
          "active_slots": 4,
          "capacity_slots": 4,
          "operating_profit": 230950.0,
          "fixed_cost_monthly": 150000.0,
          "coverage_months": 10.1
        },
        {
          "month": "2026-09",
          "realized": 366450.0,
          "at_risk": 0.0,
          "backlog_value": 14310000.0,
          "active_slots": 4,
          "capacity_slots": 4,
          "operating_profit": 216450.0,
          "fixed_cost_monthly": 150000.0,
          "coverage_months": 8.9
        },
        {
          "month": "2026-10",
          "realized": 295575.0,
          "at_risk": 70875.0,
          "backlog_value": 12436666.67,
          "active_slots": 4,
          "capacity_slots": 4,
          "operating_profit": 205818.75,
          "fixed_cost_monthly": 150000.0,
          "coverage_months": 7.7
        },
        {
          "month": "2026-11",
          "realized": 171875.0,
          "at_risk": 151375.0,
          "backlog_value": 10563333.33,
          "active_slots": 4,
          "capacity_slots": 4,
          "operating_profit": 150543.75,
          "fixed_cost_monthly": 150000.0,
          "coverage_months": 6.6
        },
        {
          "month": "2026-12",
          "realized": 160083.33,
          "at_risk": 152500.0,
          "backlog_value": 9030000.0,
          "active_slots": 4,
          "capacity_slots": 4,
          "operating_profit": 139708.33,
          "fixed_cost_monthly": 150000.0,
          "coverage_months": 5.6
        },
        {
          "month": "2027-01",
          "realized": 71750.0,
          "at_risk": 240833.33,
          "backlog_value": 7563333.33,
          "active_slots": 4,
          "capacity_slots": 4,
          "operating_profit": 126458.33,
          "fixed_cost_monthly": 150000.0,
          "coverage_months": 4.7
        },
        {
          "month": "2027-02",
          "realized": 71750.0,
          "at_risk": 240833.33,
          "backlog_value": 6096666.67,
          "active_slots": 4,
          "capacity_slots": 4,
          "operating_profit": 126458.33,
          "fixed_cost_monthly": 150000.0,
          "coverage_months": 3.8
        },
        {
          "month": "2027-03",
          "realized": 0.0,
          "at_risk": 310083.33,
          "backlog_value": 4630000.0,
          "active_slots": 4,
          "capacity_slots": 4,
          "operating_profit": 113570.83,
          "fixed_cost_monthly": 150000.0,
          "coverage_months": 2.9
        },
        {
          "month": "2027-04",
          "realized": 0.0,
          "at_risk": 316083.33,
          "backlog_value": 3286666.67,
          "active_slots": 4,
          "capacity_slots": 4,
          "operating_profit": 118670.83,
          "fixed_cost_monthly": 150000.0,
          "coverage_months": 2.0
        },
        {
          "month": "2027-05",
          "realized": 0.0,
          "at_risk": 316083.33,
          "backlog_value": 1943333.33,
          "active_slots": 4,
          "capacity_slots": 4,
          "operating_profit": 118670.83,
          "fixed_cost_monthly": 150000.0,
          "coverage_months": 1.2
        },
        {
          "month": "2027-06",
          "realized": 0.0,
          "at_risk": 78000.0,
          "backlog_value": 600000.0,
          "active_slots": 1,
          "capacity_slots": 4,
          "operating_profit": -83700.0,
          "fixed_cost_monthly": 150000.0,
          "coverage_months": 0.4
        }
      ],
      "capacity_gap": [
        {
          "month": "2026-01",
          "demand_slots": 0,
          "available_slots": 4,
          "gap": 0
        },
        {
          "month": "2026-02",
          "demand_slots": 1,
          "available_slots": 4,
          "gap": 0
        },
        {
          "month": "2026-03",
          "demand_slots": 2,
          "available_slots": 4,
          "gap": 0
        },
        {
          "month": "2026-04",
          "demand_slots": 2,
          "available_slots": 4,
          "gap": 0
        },
        {
          "month": "2026-05",
          "demand_slots": 4,
          "available_slots": 4,
          "gap": 0
        },
        {
          "month": "2026-06",
          "demand_slots": 5,
          "available_slots": 4,
          "gap": 1
        },
        {
          "month": "2026-07",
          "demand_slots": 7,
          "available_slots": 4,
          "gap": 3
        },
        {
          "month": "2026-08",
          "demand_slots": 8,
          "available_slots": 4,
          "gap": 4
        },
        {
          "month": "2026-09",
          "demand_slots": 10,
          "available_slots": 4,
          "gap": 6
        },
        {
          "month": "2026-10",
          "demand_slots": 9,
          "available_slots": 4,
          "gap": 5
        },
        {
          "month": "2026-11",
          "demand_slots": 6,
          "available_slots": 4,
          "gap": 2
        },
        {
          "month": "2026-12",
          "demand_slots": 4,
          "available_slots": 4,
          "gap": 0
        },
        {
          "month": "2027-01",
          "demand_slots": 2,
          "available_slots": 4,
          "gap": 0
        },
        {
          "month": "2027-02",
          "demand_slots": 2,
          "available_slots": 4,
          "gap": 0
        },
        {
          "month": "2027-03",
          "demand_slots": 1,
          "available_slots": 4,
          "gap": 0
        },
        {
          "month": "2027-04",
          "demand_slots": 1,
          "available_slots": 4,
          "gap": 0
        },
        {
          "month": "2027-05",
          "demand_slots": 0,
          "available_slots": 4,
          "gap": 0
        },
        {
          "month": "2027-06",
          "demand_slots": 0,
          "available_slots": 4,
          "gap": 0
        }
      ],
      "headcount_roi": {
        "added_teams": 1,
        "baseline_teams": 3,
        "incremental_pv_margin": 1960427.4,
        "quality_pv_gain": 841871.36,
        "throughput_pv_gain": 1118556.05,
        "initial_cost": 200000.0,
        "annual_cost": 1600000.0,
        "total_cost": 2427463.96,
        "cost_valid": true,
        "raw_multiple": 0.808,
        "roi_pct": -19.2,
        "npv": -467036.55,
        "payback_months": null,
        "discount_rate": 0.1,
        "revenue_realization": 0.85
      },
      "sensitivity": [
        {
          "factor": "Cost per team",
          "low": -31.8,
          "high": -1.1,
          "swing": 30.7
        },
        {
          "factor": "Revenue realization",
          "low": -25.9,
          "high": -12.6,
          "swing": 13.3
        },
        {
          "factor": "Delivery teams",
          "low": -31.0,
          "high": -19.2,
          "swing": 11.8
        },
        {
          "factor": "Order-intake growth",
          "low": -24.7,
          "high": -13.8,
          "swing": 10.9
        },
        {
          "factor": "Delay shock",
          "low": -21.9,
          "high": -19.8,
          "swing": 2.1
        }
      ],
      "summary": {
        "company": "Meridian Technologies",
        "backlog_projects": 11,
        "backlog_value": 29230000.0,
        "horizon_months": 18,
        "realized_total": 3976333.32,
        "at_risk_total": 1876666.65,
        "at_risk_share_pct": 32.1,
        "months_capacity_short": 6,
        "backlog_cleared_pct": 97.9,
        "operating_profit_total": 2871499.97,
        "op_margin_pct": 51.5,
        "coverage_months_now": 18.2,
        "coverage_warning_month": "2026-12",
        "fixed_cost_base_monthly": 150000.0
      },
      "stress_timeline": null,
      "stress_comparison": null
    }
  },
  {
    "id": "starter",
    "label": "Build Your Own",
    "description": "A blank 3-project canvas \u2014 set your own book, crews, and costs, then add a crew to test it.",
    "backlog": [
      {
        "id": "NEW-1",
        "name": "Project A",
        "contract_value": 120000,
        "gross_margin_pct": 0.35,
        "duration_months": 4,
        "order_intake_date": "2026-01",
        "promised_delivery_date": "2026-07",
        "priority": 1
      },
      {
        "id": "NEW-2",
        "name": "Project B",
        "contract_value": 80000,
        "gross_margin_pct": 0.35,
        "duration_months": 3,
        "order_intake_date": "2026-02",
        "promised_delivery_date": "2026-06",
        "priority": 2
      },
      {
        "id": "NEW-3",
        "name": "Project C",
        "contract_value": 50000,
        "gross_margin_pct": 0.35,
        "duration_months": 2,
        "order_intake_date": "2026-02",
        "promised_delivery_date": "2026-05",
        "priority": 2
      }
    ],
    "inputs": {
      "delay_shock_months": 0,
      "discount_rate": 0.1,
      "revenue_realization": 0.85,
      "horizon_months": 18,
      "anchor_month": "2026-01",
      "delivery_teams": 1,
      "baseline_teams": 1,
      "order_intake_growth": 0.12,
      "cost_per_team": 120000,
      "ramp_cost_per_team": 10000,
      "fixed_cost_base_monthly": 0,
      "run_stress": false
    },
    "result": {
      "timeline": [
        {
          "month": "2026-01",
          "realized": 10500.0,
          "at_risk": 0.0,
          "backlog_value": 250000.0,
          "active_slots": 1,
          "capacity_slots": 1,
          "operating_profit": 10500.0,
          "fixed_cost_monthly": 0.0,
          "coverage_months": 9.0
        },
        {
          "month": "2026-02",
          "realized": 10500.0,
          "at_risk": 0.0,
          "backlog_value": 220000.0,
          "active_slots": 1,
          "capacity_slots": 1,
          "operating_profit": 10500.0,
          "fixed_cost_monthly": 0.0,
          "coverage_months": 7.9
        },
        {
          "month": "2026-03",
          "realized": 10500.0,
          "at_risk": 0.0,
          "backlog_value": 190000.0,
          "active_slots": 1,
          "capacity_slots": 1,
          "operating_profit": 10500.0,
          "fixed_cost_monthly": 0.0,
          "coverage_months": 6.8
        },
        {
          "month": "2026-04",
          "realized": 10500.0,
          "at_risk": 0.0,
          "backlog_value": 160000.0,
          "active_slots": 1,
          "capacity_slots": 1,
          "operating_profit": 10500.0,
          "fixed_cost_monthly": 0.0,
          "coverage_months": 5.8
        },
        {
          "month": "2026-05",
          "realized": 0.0,
          "at_risk": 8750.0,
          "backlog_value": 130000.0,
          "active_slots": 1,
          "capacity_slots": 1,
          "operating_profit": 7437.5,
          "fixed_cost_monthly": 0.0,
          "coverage_months": 4.7
        },
        {
          "month": "2026-06",
          "realized": 0.0,
          "at_risk": 8750.0,
          "backlog_value": 105000.0,
          "active_slots": 1,
          "capacity_slots": 1,
          "operating_profit": 7437.5,
          "fixed_cost_monthly": 0.0,
          "coverage_months": 3.8
        },
        {
          "month": "2026-07",
          "realized": 0.0,
          "at_risk": 9333.33,
          "backlog_value": 80000.0,
          "active_slots": 1,
          "capacity_slots": 1,
          "operating_profit": 7933.33,
          "fixed_cost_monthly": 0.0,
          "coverage_months": 2.9
        },
        {
          "month": "2026-08",
          "realized": 0.0,
          "at_risk": 9333.33,
          "backlog_value": 53333.33,
          "active_slots": 1,
          "capacity_slots": 1,
          "operating_profit": 7933.33,
          "fixed_cost_monthly": 0.0,
          "coverage_months": 1.9
        },
        {
          "month": "2026-09",
          "realized": 0.0,
          "at_risk": 9333.33,
          "backlog_value": 26666.67,
          "active_slots": 1,
          "capacity_slots": 1,
          "operating_profit": 7933.33,
          "fixed_cost_monthly": 0.0,
          "coverage_months": 1.0
        },
        {
          "month": "2026-10",
          "realized": 0.0,
          "at_risk": 0.0,
          "backlog_value": 0.0,
          "active_slots": 0,
          "capacity_slots": 1,
          "operating_profit": 0.0,
          "fixed_cost_monthly": 0.0,
          "coverage_months": 0.0
        },
        {
          "month": "2026-11",
          "realized": 0.0,
          "at_risk": 0.0,
          "backlog_value": 0.0,
          "active_slots": 0,
          "capacity_slots": 1,
          "operating_profit": 0.0,
          "fixed_cost_monthly": 0.0,
          "coverage_months": 0.0
        },
        {
          "month": "2026-12",
          "realized": 0.0,
          "at_risk": 0.0,
          "backlog_value": 0.0,
          "active_slots": 0,
          "capacity_slots": 1,
          "operating_profit": 0.0,
          "fixed_cost_monthly": 0.0,
          "coverage_months": 0.0
        },
        {
          "month": "2027-01",
          "realized": 0.0,
          "at_risk": 0.0,
          "backlog_value": 0.0,
          "active_slots": 0,
          "capacity_slots": 1,
          "operating_profit": 0.0,
          "fixed_cost_monthly": 0.0,
          "coverage_months": 0.0
        },
        {
          "month": "2027-02",
          "realized": 0.0,
          "at_risk": 0.0,
          "backlog_value": 0.0,
          "active_slots": 0,
          "capacity_slots": 1,
          "operating_profit": 0.0,
          "fixed_cost_monthly": 0.0,
          "coverage_months": 0.0
        },
        {
          "month": "2027-03",
          "realized": 0.0,
          "at_risk": 0.0,
          "backlog_value": 0.0,
          "active_slots": 0,
          "capacity_slots": 1,
          "operating_profit": 0.0,
          "fixed_cost_monthly": 0.0,
          "coverage_months": 0.0
        },
        {
          "month": "2027-04",
          "realized": 0.0,
          "at_risk": 0.0,
          "backlog_value": 0.0,
          "active_slots": 0,
          "capacity_slots": 1,
          "operating_profit": 0.0,
          "fixed_cost_monthly": 0.0,
          "coverage_months": 0.0
        },
        {
          "month": "2027-05",
          "realized": 0.0,
          "at_risk": 0.0,
          "backlog_value": 0.0,
          "active_slots": 0,
          "capacity_slots": 1,
          "operating_profit": 0.0,
          "fixed_cost_monthly": 0.0,
          "coverage_months": 0.0
        },
        {
          "month": "2027-06",
          "realized": 0.0,
          "at_risk": 0.0,
          "backlog_value": 0.0,
          "active_slots": 0,
          "capacity_slots": 1,
          "operating_profit": 0.0,
          "fixed_cost_monthly": 0.0,
          "coverage_months": 0.0
        }
      ],
      "capacity_gap": [
        {
          "month": "2026-01",
          "demand_slots": 0,
          "available_slots": 1,
          "gap": 0
        },
        {
          "month": "2026-02",
          "demand_slots": 0,
          "available_slots": 1,
          "gap": 0
        },
        {
          "month": "2026-03",
          "demand_slots": 3,
          "available_slots": 1,
          "gap": 2
        },
        {
          "month": "2026-04",
          "demand_slots": 3,
          "available_slots": 1,
          "gap": 2
        },
        {
          "month": "2026-05",
          "demand_slots": 2,
          "available_slots": 1,
          "gap": 1
        },
        {
          "month": "2026-06",
          "demand_slots": 1,
          "available_slots": 1,
          "gap": 0
        },
        {
          "month": "2026-07",
          "demand_slots": 0,
          "available_slots": 1,
          "gap": 0
        },
        {
          "month": "2026-08",
          "demand_slots": 0,
          "available_slots": 1,
          "gap": 0
        },
        {
          "month": "2026-09",
          "demand_slots": 0,
          "available_slots": 1,
          "gap": 0
        },
        {
          "month": "2026-10",
          "demand_slots": 0,
          "available_slots": 1,
          "gap": 0
        },
        {
          "month": "2026-11",
          "demand_slots": 0,
          "available_slots": 1,
          "gap": 0
        },
        {
          "month": "2026-12",
          "demand_slots": 0,
          "available_slots": 1,
          "gap": 0
        },
        {
          "month": "2027-01",
          "demand_slots": 0,
          "available_slots": 1,
          "gap": 0
        },
        {
          "month": "2027-02",
          "demand_slots": 0,
          "available_slots": 1,
          "gap": 0
        },
        {
          "month": "2027-03",
          "demand_slots": 0,
          "available_slots": 1,
          "gap": 0
        },
        {
          "month": "2027-04",
          "demand_slots": 0,
          "available_slots": 1,
          "gap": 0
        },
        {
          "month": "2027-05",
          "demand_slots": 0,
          "available_slots": 1,
          "gap": 0
        },
        {
          "month": "2027-06",
          "demand_slots": 0,
          "available_slots": 1,
          "gap": 0
        }
      ],
      "headcount_roi": {
        "added_teams": 0,
        "baseline_teams": 1,
        "incremental_pv_margin": 0.0,
        "quality_pv_gain": 0.0,
        "throughput_pv_gain": 0.0,
        "initial_cost": 0.0,
        "annual_cost": 0.0,
        "total_cost": 0.0,
        "cost_valid": false,
        "raw_multiple": null,
        "roi_pct": null,
        "npv": 0.0,
        "payback_months": null,
        "discount_rate": 0.1,
        "revenue_realization": 0.85
      },
      "sensitivity": [
        {
          "factor": "Delivery teams",
          "low": -30.2,
          "high": -30.2,
          "swing": 0.0
        }
      ],
      "summary": {
        "company": "Meridian Technologies",
        "backlog_projects": 3,
        "backlog_value": 250000.0,
        "horizon_months": 18,
        "realized_total": 42000.0,
        "at_risk_total": 45499.99,
        "at_risk_share_pct": 52.0,
        "months_capacity_short": 3,
        "backlog_cleared_pct": 100.0,
        "operating_profit_total": 80674.99,
        "op_margin_pct": 100.0,
        "coverage_months_now": 9.0,
        "coverage_warning_month": "2026-04",
        "fixed_cost_base_monthly": 0.0
      },
      "stress_timeline": null,
      "stress_comparison": null
    }
  }
]

export const FALLBACK_RESULT = {
  "timeline": [
    {
      "month": "2026-01",
      "realized": 241428.57,
      "at_risk": 0.0,
      "backlog_value": 29230000.0,
      "active_slots": 2,
      "capacity_slots": 4,
      "operating_profit": 91428.57,
      "fixed_cost_monthly": 150000.0,
      "coverage_months": 18.0
    },
    {
      "month": "2026-02",
      "realized": 336428.57,
      "at_risk": 0.0,
      "backlog_value": 27987142.86,
      "active_slots": 3,
      "capacity_slots": 4,
      "operating_profit": 186428.57,
      "fixed_cost_monthly": 150000.0,
      "coverage_months": 17.2
    },
    {
      "month": "2026-03",
      "realized": 336428.57,
      "at_risk": 0.0,
      "backlog_value": 26244285.71,
      "active_slots": 3,
      "capacity_slots": 4,
      "operating_profit": 186428.57,
      "fixed_cost_monthly": 150000.0,
      "coverage_months": 16.2
    },
    {
      "month": "2026-04",
      "realized": 436303.57,
      "at_risk": 0.0,
      "backlog_value": 24501428.57,
      "active_slots": 4,
      "capacity_slots": 4,
      "operating_profit": 286303.57,
      "fixed_cost_monthly": 150000.0,
      "coverage_months": 15.1
    },
    {
      "month": "2026-05",
      "realized": 436303.57,
      "at_risk": 0.0,
      "backlog_value": 22171071.43,
      "active_slots": 4,
      "capacity_slots": 4,
      "operating_profit": 286303.57,
      "fixed_cost_monthly": 150000.0,
      "coverage_months": 13.7
    },
    {
      "month": "2026-06",
      "realized": 436303.57,
      "at_risk": 0.0,
      "backlog_value": 19840714.29,
      "active_slots": 4,
      "capacity_slots": 4,
      "operating_profit": 286303.57,
      "fixed_cost_monthly": 150000.0,
      "coverage_months": 12.2
    },
    {
      "month": "2026-07",
      "realized": 436303.57,
      "at_risk": 0.0,
      "backlog_value": 17510357.14,
      "active_slots": 4,
      "capacity_slots": 4,
      "operating_profit": 286303.57,
      "fixed_cost_monthly": 150000.0,
      "coverage_months": 10.8
    },
    {
      "month": "2026-08",
      "realized": 409750.0,
      "at_risk": 0.0,
      "backlog_value": 15180000.0,
      "active_slots": 4,
      "capacity_slots": 4,
      "operating_profit": 259750.0,
      "fixed_cost_monthly": 150000.0,
      "coverage_months": 9.3
    },
    {
      "month": "2026-09",
      "realized": 323250.0,
      "at_risk": 0.0,
      "backlog_value": 13030000.0,
      "active_slots": 4,
      "capacity_slots": 4,
      "operating_profit": 173250.0,
      "fixed_cost_monthly": 150000.0,
      "coverage_months": 8.0
    },
    {
      "month": "2026-10",
      "realized": 252375.0,
      "at_risk": 70875.0,
      "backlog_value": 11496666.67,
      "active_slots": 4,
      "capacity_slots": 4,
      "operating_profit": 162618.75,
      "fixed_cost_monthly": 150000.0,
      "coverage_months": 7.1
    },
    {
      "month": "2026-11",
      "realized": 171875.0,
      "at_risk": 151375.0,
      "backlog_value": 9963333.33,
      "active_slots": 4,
      "capacity_slots": 4,
      "operating_profit": 150543.75,
      "fixed_cost_monthly": 150000.0,
      "coverage_months": 6.1
    },
    {
      "month": "2026-12",
      "realized": 160083.33,
      "at_risk": 152500.0,
      "backlog_value": 8430000.0,
      "active_slots": 4,
      "capacity_slots": 4,
      "operating_profit": 139708.33,
      "fixed_cost_monthly": 150000.0,
      "coverage_months": 5.2
    },
    {
      "month": "2027-01",
      "realized": 71750.0,
      "at_risk": 240833.33,
      "backlog_value": 6963333.33,
      "active_slots": 4,
      "capacity_slots": 4,
      "operating_profit": 126458.33,
      "fixed_cost_monthly": 150000.0,
      "coverage_months": 4.3
    },
    {
      "month": "2027-02",
      "realized": 71750.0,
      "at_risk": 246833.33,
      "backlog_value": 5496666.67,
      "active_slots": 4,
      "capacity_slots": 4,
      "operating_profit": 131558.33,
      "fixed_cost_monthly": 150000.0,
      "coverage_months": 3.4
    },
    {
      "month": "2027-03",
      "realized": 0.0,
      "at_risk": 316083.33,
      "backlog_value": 4070000.0,
      "active_slots": 4,
      "capacity_slots": 4,
      "operating_profit": 118670.83,
      "fixed_cost_monthly": 150000.0,
      "coverage_months": 2.5
    },
    {
      "month": "2027-04",
      "realized": 0.0,
      "at_risk": 316083.33,
      "backlog_value": 2726666.67,
      "active_slots": 4,
      "capacity_slots": 4,
      "operating_profit": 118670.83,
      "fixed_cost_monthly": 150000.0,
      "coverage_months": 1.7
    },
    {
      "month": "2027-05",
      "realized": 0.0,
      "at_risk": 238083.33,
      "backlog_value": 1383333.33,
      "active_slots": 3,
      "capacity_slots": 4,
      "operating_profit": 52370.83,
      "fixed_cost_monthly": 150000.0,
      "coverage_months": 0.9
    },
    {
      "month": "2027-06",
      "realized": 0.0,
      "at_risk": 78000.0,
      "backlog_value": 300000.0,
      "active_slots": 1,
      "capacity_slots": 4,
      "operating_profit": -83700.0,
      "fixed_cost_monthly": 150000.0,
      "coverage_months": 0.2
    }
  ],
  "capacity_gap": [
    {
      "month": "2026-01",
      "demand_slots": 0,
      "available_slots": 4,
      "gap": 0
    },
    {
      "month": "2026-02",
      "demand_slots": 1,
      "available_slots": 4,
      "gap": 0
    },
    {
      "month": "2026-03",
      "demand_slots": 2,
      "available_slots": 4,
      "gap": 0
    },
    {
      "month": "2026-04",
      "demand_slots": 2,
      "available_slots": 4,
      "gap": 0
    },
    {
      "month": "2026-05",
      "demand_slots": 4,
      "available_slots": 4,
      "gap": 0
    },
    {
      "month": "2026-06",
      "demand_slots": 5,
      "available_slots": 4,
      "gap": 1
    },
    {
      "month": "2026-07",
      "demand_slots": 7,
      "available_slots": 4,
      "gap": 3
    },
    {
      "month": "2026-08",
      "demand_slots": 8,
      "available_slots": 4,
      "gap": 4
    },
    {
      "month": "2026-09",
      "demand_slots": 10,
      "available_slots": 4,
      "gap": 6
    },
    {
      "month": "2026-10",
      "demand_slots": 9,
      "available_slots": 4,
      "gap": 5
    },
    {
      "month": "2026-11",
      "demand_slots": 6,
      "available_slots": 4,
      "gap": 2
    },
    {
      "month": "2026-12",
      "demand_slots": 4,
      "available_slots": 4,
      "gap": 0
    },
    {
      "month": "2027-01",
      "demand_slots": 2,
      "available_slots": 4,
      "gap": 0
    },
    {
      "month": "2027-02",
      "demand_slots": 2,
      "available_slots": 4,
      "gap": 0
    },
    {
      "month": "2027-03",
      "demand_slots": 1,
      "available_slots": 4,
      "gap": 0
    },
    {
      "month": "2027-04",
      "demand_slots": 1,
      "available_slots": 4,
      "gap": 0
    },
    {
      "month": "2027-05",
      "demand_slots": 0,
      "available_slots": 4,
      "gap": 0
    },
    {
      "month": "2027-06",
      "demand_slots": 0,
      "available_slots": 4,
      "gap": 0
    }
  ],
  "headcount_roi": {
    "added_teams": 1,
    "baseline_teams": 3,
    "incremental_pv_margin": 1895956.64,
    "quality_pv_gain": 777400.59,
    "throughput_pv_gain": 1118556.05,
    "initial_cost": 200000.0,
    "annual_cost": 1000000.0,
    "total_cost": 1592164.97,
    "cost_valid": true,
    "raw_multiple": 1.191,
    "roi_pct": 19.1,
    "npv": 303791.66,
    "payback_months": 6,
    "discount_rate": 0.1,
    "revenue_realization": 0.85
  },
  "sensitivity": [
    {
      "factor": "Cost per team",
      "low": 1.4,
      "high": 44.3,
      "swing": 42.9
    },
    {
      "factor": "Revenue realization",
      "low": 9.3,
      "high": 28.9,
      "swing": 19.6
    },
    {
      "factor": "Delivery teams",
      "low": 1.3,
      "high": 19.1,
      "swing": 17.8
    },
    {
      "factor": "Order-intake growth",
      "low": 10.8,
      "high": 27.3,
      "swing": 16.5
    },
    {
      "factor": "Delay shock",
      "low": 19.1,
      "high": 22.2,
      "swing": 3.1
    }
  ],
  "summary": {
    "company": "Meridian Technologies",
    "backlog_projects": 11,
    "backlog_value": 29230000.0,
    "horizon_months": 18,
    "realized_total": 4120333.32,
    "at_risk_total": 1810666.65,
    "at_risk_share_pct": 30.5,
    "months_capacity_short": 6,
    "backlog_cleared_pct": 99.0,
    "operating_profit_total": 2959399.97,
    "op_margin_pct": 52.3,
    "coverage_months_now": 18.0,
    "coverage_warning_month": "2026-12",
    "fixed_cost_base_monthly": 150000.0
  },
  "stress_timeline": null,
  "stress_comparison": null
}
