// Auto-generated by data-generation/project1/generate_fallback.py
// Do not edit manually — regenerate with: python generate_fallback.py

export const FALLBACK_DATA = {
  "summary": {
    "total_revenue": 423937057.87,
    "ebitda": 126069951.78999999,
    "ebitda_margin": 29.7,
    "free_cash_flow": 55382026.230000004,
    "ccc": 11.2,
    "revenue_sparkline": [
      14348885.13,
      14856900.75,
      15561562.68,
      16362111.969999999,
      16392950.0,
      16894306.51,
      16393364.09,
      16270576.08,
      17538340.85,
      18241976.73,
      18537051.15,
      19423407.17,
      16227113.32,
      16910141.16,
      17351590.57,
      18141691.11,
      18763758.92,
      19163302.46,
      18750000.220000003,
      18075153.64,
      18709526.93,
      19962470.05,
      20085533.82,
      20975342.560000002
    ],
    "ebitda_sparkline": [
      4236744.59,
      4465343.9,
      4383637.85,
      5161458.06,
      5358129.26,
      4675012.45,
      4944860.54,
      4930110.76,
      5139031.85,
      5256390.83,
      5409763.6899999995,
      5703675.85,
      4724576.01,
      4709690.24,
      5266688.1,
      5040032.75,
      5713502.97,
      5647254.58,
      5742230.6,
      5518420.9399999995,
      5499397.84,
      5951751.3100000005,
      6387666.9,
      6204579.92
    ],
    "fcf_sparkline": [
      2122254.55,
      1542352.16,
      1064192.31,
      2154334.59,
      2618979.29,
      2071596.82,
      3175604.4699999997,
      2494904.3699999996,
      1885566.4600000002,
      1400709.3400000003,
      2911781.1800000006,
      1572237.1700000004,
      5521912.99,
      1635490.6500000004,
      1746138.7200000002,
      1936648.01,
      1848014.2899999996,
      1727409.5699999998,
      3206560.24,
      3656415.1399999997,
      1920862.2,
      1764297.1800000002,
      2688676.62,
      2715087.91
    ],
    "ccc_sparkline": [
      5.133333333333333,
      5.233333333333333,
      8.966666666666667,
      8.5,
      11.266666666666666,
      10.9,
      10.066666666666668,
      10.799999999999999,
      11.533333333333331,
      13.6,
      13.666666666666666,
      13.1,
      23.3,
      7.066666666666667,
      7.6000000000000005,
      8.433333333333334,
      9.299999999999999,
      11.966666666666667,
      11.266666666666667,
      12.833333333333334,
      10.333333333333334,
      14.266666666666666,
      16.400000000000002,
      14.066666666666668
    ]
  },
  "pnl_by_division": [
    {
      "month": "2023-01",
      "Cloud Infrastructure": 3641344.72,
      "Enterprise Software": 6314697.25,
      "Professional Services": 4392843.16
    },
    {
      "month": "2023-02",
      "Cloud Infrastructure": 3721488.05,
      "Enterprise Software": 6636557.69,
      "Professional Services": 4498855.01
    },
    {
      "month": "2023-03",
      "Cloud Infrastructure": 3901005.02,
      "Enterprise Software": 6930641.14,
      "Professional Services": 4729916.52
    },
    {
      "month": "2023-04",
      "Cloud Infrastructure": 4003823.23,
      "Enterprise Software": 7444481.02,
      "Professional Services": 4913807.72
    },
    {
      "month": "2023-05",
      "Cloud Infrastructure": 4143933.46,
      "Enterprise Software": 7335585.69,
      "Professional Services": 4913430.85
    },
    {
      "month": "2023-06",
      "Cloud Infrastructure": 4122739.49,
      "Enterprise Software": 7570633.74,
      "Professional Services": 5200933.28
    },
    {
      "month": "2023-07",
      "Cloud Infrastructure": 4058232.98,
      "Enterprise Software": 7289672.97,
      "Professional Services": 5045458.14
    },
    {
      "month": "2023-08",
      "Cloud Infrastructure": 4023613.04,
      "Enterprise Software": 7236260.81,
      "Professional Services": 5010702.23
    },
    {
      "month": "2023-09",
      "Cloud Infrastructure": 4588324.64,
      "Enterprise Software": 7513818.88,
      "Professional Services": 5436197.33
    },
    {
      "month": "2023-10",
      "Cloud Infrastructure": 4835544.62,
      "Enterprise Software": 7896252.43,
      "Professional Services": 5510179.68
    },
    {
      "month": "2023-11",
      "Cloud Infrastructure": 4904545.58,
      "Enterprise Software": 7826892.13,
      "Professional Services": 5805613.44
    },
    {
      "month": "2023-12",
      "Cloud Infrastructure": 5062554.33,
      "Enterprise Software": 8383572.55,
      "Professional Services": 5977280.29
    },
    {
      "month": "2024-01",
      "Cloud Infrastructure": 4283317.11,
      "Enterprise Software": 6938025.76,
      "Professional Services": 5005770.45
    },
    {
      "month": "2024-02",
      "Cloud Infrastructure": 4422039.69,
      "Enterprise Software": 7155078.21,
      "Professional Services": 5333023.26
    },
    {
      "month": "2024-03",
      "Cloud Infrastructure": 4886707.05,
      "Enterprise Software": 7244417.9,
      "Professional Services": 5220465.62
    },
    {
      "month": "2024-04",
      "Cloud Infrastructure": 4946785.73,
      "Enterprise Software": 7851752.15,
      "Professional Services": 5343153.23
    },
    {
      "month": "2024-05",
      "Cloud Infrastructure": 5050065.08,
      "Enterprise Software": 8073395.16,
      "Professional Services": 5640298.68
    },
    {
      "month": "2024-06",
      "Cloud Infrastructure": 5029765.5,
      "Enterprise Software": 8547777.27,
      "Professional Services": 5585759.69
    },
    {
      "month": "2024-07",
      "Cloud Infrastructure": 4621737.14,
      "Enterprise Software": 8552031.64,
      "Professional Services": 5576231.44
    },
    {
      "month": "2024-08",
      "Cloud Infrastructure": 4440350.38,
      "Enterprise Software": 8255398.37,
      "Professional Services": 5379404.89
    },
    {
      "month": "2024-09",
      "Cloud Infrastructure": 4696992.13,
      "Enterprise Software": 8565928.81,
      "Professional Services": 5446605.99
    },
    {
      "month": "2024-10",
      "Cloud Infrastructure": 5099327.99,
      "Enterprise Software": 9236218.26,
      "Professional Services": 5626923.8
    },
    {
      "month": "2024-11",
      "Cloud Infrastructure": 5273509.88,
      "Enterprise Software": 9252268.73,
      "Professional Services": 5559755.21
    },
    {
      "month": "2024-12",
      "Cloud Infrastructure": 5392473.64,
      "Enterprise Software": 9481364.27,
      "Professional Services": 6101504.65
    }
  ],
  "div_detail": [
    {
      "month": "2023-01",
      "Enterprise Software_revenue": 6314697.25,
      "Enterprise Software_ebitda": 1872069.94,
      "Enterprise Software_gross_margin": 66.28,
      "Professional Services_revenue": 4392843.16,
      "Professional Services_ebitda": 1228536.63,
      "Professional Services_gross_margin": 57.25,
      "Cloud Infrastructure_revenue": 3641344.72,
      "Cloud Infrastructure_ebitda": 1136138.02,
      "Cloud Infrastructure_gross_margin": 62.01
    },
    {
      "month": "2023-02",
      "Enterprise Software_revenue": 6636557.69,
      "Enterprise Software_ebitda": 2074281.19,
      "Enterprise Software_gross_margin": 66.87,
      "Professional Services_revenue": 4498855.01,
      "Professional Services_ebitda": 1315187.48,
      "Professional Services_gross_margin": 50.45,
      "Cloud Infrastructure_revenue": 3721488.05,
      "Cloud Infrastructure_ebitda": 1075875.23,
      "Cloud Infrastructure_gross_margin": 59.81
    },
    {
      "month": "2023-03",
      "Enterprise Software_revenue": 6930641.14,
      "Enterprise Software_ebitda": 1638529.27,
      "Enterprise Software_gross_margin": 67.42,
      "Professional Services_revenue": 4729916.52,
      "Professional Services_ebitda": 1698896.86,
      "Professional Services_gross_margin": 57.25,
      "Cloud Infrastructure_revenue": 3901005.02,
      "Cloud Infrastructure_ebitda": 1046211.72,
      "Cloud Infrastructure_gross_margin": 60.36
    },
    {
      "month": "2023-04",
      "Enterprise Software_revenue": 7444481.02,
      "Enterprise Software_ebitda": 2196870.01,
      "Enterprise Software_gross_margin": 64.46,
      "Professional Services_revenue": 4913807.72,
      "Professional Services_ebitda": 1653107.28,
      "Professional Services_gross_margin": 53.86,
      "Cloud Infrastructure_revenue": 4003823.23,
      "Cloud Infrastructure_ebitda": 1311480.77,
      "Cloud Infrastructure_gross_margin": 61.28
    },
    {
      "month": "2023-05",
      "Enterprise Software_revenue": 7335585.69,
      "Enterprise Software_ebitda": 2460798.63,
      "Enterprise Software_gross_margin": 68.02,
      "Professional Services_revenue": 4913430.85,
      "Professional Services_ebitda": 1434468.59,
      "Professional Services_gross_margin": 49.96,
      "Cloud Infrastructure_revenue": 4143933.46,
      "Cloud Infrastructure_ebitda": 1462862.04,
      "Cloud Infrastructure_gross_margin": 64.55
    },
    {
      "month": "2023-06",
      "Enterprise Software_revenue": 7570633.74,
      "Enterprise Software_ebitda": 2204906.52,
      "Enterprise Software_gross_margin": 67.23,
      "Professional Services_revenue": 5200933.28,
      "Professional Services_ebitda": 1301958.11,
      "Professional Services_gross_margin": 47.73,
      "Cloud Infrastructure_revenue": 4122739.49,
      "Cloud Infrastructure_ebitda": 1168147.82,
      "Cloud Infrastructure_gross_margin": 60.44
    },
    {
      "month": "2023-07",
      "Enterprise Software_revenue": 7289672.97,
      "Enterprise Software_ebitda": 1945076.11,
      "Enterprise Software_gross_margin": 63.18,
      "Professional Services_revenue": 5045458.14,
      "Professional Services_ebitda": 1577480.61,
      "Professional Services_gross_margin": 51.54,
      "Cloud Infrastructure_revenue": 4058232.98,
      "Cloud Infrastructure_ebitda": 1422303.82,
      "Cloud Infrastructure_gross_margin": 63.22
    },
    {
      "month": "2023-08",
      "Enterprise Software_revenue": 7236260.81,
      "Enterprise Software_ebitda": 2232091.48,
      "Enterprise Software_gross_margin": 64.82,
      "Professional Services_revenue": 5010702.23,
      "Professional Services_ebitda": 1521143.01,
      "Professional Services_gross_margin": 49.93,
      "Cloud Infrastructure_revenue": 4023613.04,
      "Cloud Infrastructure_ebitda": 1176876.27,
      "Cloud Infrastructure_gross_margin": 59.29
    },
    {
      "month": "2023-09",
      "Enterprise Software_revenue": 7513818.88,
      "Enterprise Software_ebitda": 1992591.82,
      "Enterprise Software_gross_margin": 62.32,
      "Professional Services_revenue": 5436197.33,
      "Professional Services_ebitda": 1481872.04,
      "Professional Services_gross_margin": 49.37,
      "Cloud Infrastructure_revenue": 4588324.64,
      "Cloud Infrastructure_ebitda": 1664567.99,
      "Cloud Infrastructure_gross_margin": 64.67
    },
    {
      "month": "2023-10",
      "Enterprise Software_revenue": 7896252.43,
      "Enterprise Software_ebitda": 2054535.72,
      "Enterprise Software_gross_margin": 67.23,
      "Professional Services_revenue": 5510179.68,
      "Professional Services_ebitda": 1628113.93,
      "Professional Services_gross_margin": 50.75,
      "Cloud Infrastructure_revenue": 4835544.62,
      "Cloud Infrastructure_ebitda": 1573741.18,
      "Cloud Infrastructure_gross_margin": 62.81
    },
    {
      "month": "2023-11",
      "Enterprise Software_revenue": 7826892.13,
      "Enterprise Software_ebitda": 2177479.81,
      "Enterprise Software_gross_margin": 63.06,
      "Professional Services_revenue": 5805613.44,
      "Professional Services_ebitda": 1853551.23,
      "Professional Services_gross_margin": 51.67,
      "Cloud Infrastructure_revenue": 4904545.58,
      "Cloud Infrastructure_ebitda": 1378732.65,
      "Cloud Infrastructure_gross_margin": 62.11
    },
    {
      "month": "2023-12",
      "Enterprise Software_revenue": 8383572.55,
      "Enterprise Software_ebitda": 2700398.79,
      "Enterprise Software_gross_margin": 67.34,
      "Professional Services_revenue": 5977280.29,
      "Professional Services_ebitda": 1484363.3,
      "Professional Services_gross_margin": 46.45,
      "Cloud Infrastructure_revenue": 5062554.33,
      "Cloud Infrastructure_ebitda": 1518913.76,
      "Cloud Infrastructure_gross_margin": 59.81
    },
    {
      "month": "2024-01",
      "Enterprise Software_revenue": 6938025.76,
      "Enterprise Software_ebitda": 1693484.87,
      "Enterprise Software_gross_margin": 60.98,
      "Professional Services_revenue": 5005770.45,
      "Professional Services_ebitda": 1527385.91,
      "Professional Services_gross_margin": 51.36,
      "Cloud Infrastructure_revenue": 4283317.11,
      "Cloud Infrastructure_ebitda": 1503705.23,
      "Cloud Infrastructure_gross_margin": 64.9
    },
    {
      "month": "2024-02",
      "Enterprise Software_revenue": 7155078.21,
      "Enterprise Software_ebitda": 2014395.64,
      "Enterprise Software_gross_margin": 64.34,
      "Professional Services_revenue": 5333023.26,
      "Professional Services_ebitda": 1263788.62,
      "Professional Services_gross_margin": 44.84,
      "Cloud Infrastructure_revenue": 4422039.69,
      "Cloud Infrastructure_ebitda": 1431505.98,
      "Cloud Infrastructure_gross_margin": 63.2
    },
    {
      "month": "2024-03",
      "Enterprise Software_revenue": 7244417.9,
      "Enterprise Software_ebitda": 2054733.65,
      "Enterprise Software_gross_margin": 66.06,
      "Professional Services_revenue": 5220465.62,
      "Professional Services_ebitda": 1699655.19,
      "Professional Services_gross_margin": 52.27,
      "Cloud Infrastructure_revenue": 4886707.05,
      "Cloud Infrastructure_ebitda": 1512299.26,
      "Cloud Infrastructure_gross_margin": 61.84
    },
    {
      "month": "2024-04",
      "Enterprise Software_revenue": 7851752.15,
      "Enterprise Software_ebitda": 2198867.15,
      "Enterprise Software_gross_margin": 62.51,
      "Professional Services_revenue": 5343153.23,
      "Professional Services_ebitda": 1385456.03,
      "Professional Services_gross_margin": 48.2,
      "Cloud Infrastructure_revenue": 4946785.73,
      "Cloud Infrastructure_ebitda": 1455709.57,
      "Cloud Infrastructure_gross_margin": 58.85
    },
    {
      "month": "2024-05",
      "Enterprise Software_revenue": 8073395.16,
      "Enterprise Software_ebitda": 2501306.35,
      "Enterprise Software_gross_margin": 64.82,
      "Professional Services_revenue": 5640298.68,
      "Professional Services_ebitda": 1702842.03,
      "Professional Services_gross_margin": 51.92,
      "Cloud Infrastructure_revenue": 5050065.08,
      "Cloud Infrastructure_ebitda": 1509354.59,
      "Cloud Infrastructure_gross_margin": 59.85
    },
    {
      "month": "2024-06",
      "Enterprise Software_revenue": 8547777.27,
      "Enterprise Software_ebitda": 3149537.52,
      "Enterprise Software_gross_margin": 72.0,
      "Professional Services_revenue": 5585759.69,
      "Professional Services_ebitda": 1562344.23,
      "Professional Services_gross_margin": 48.82,
      "Cloud Infrastructure_revenue": 5029765.5,
      "Cloud Infrastructure_ebitda": 935372.83,
      "Cloud Infrastructure_gross_margin": 55.72
    },
    {
      "month": "2024-07",
      "Enterprise Software_revenue": 8552031.64,
      "Enterprise Software_ebitda": 2496115.35,
      "Enterprise Software_gross_margin": 64.61,
      "Professional Services_revenue": 5576231.44,
      "Professional Services_ebitda": 1965023.87,
      "Professional Services_gross_margin": 54.75,
      "Cloud Infrastructure_revenue": 4621737.14,
      "Cloud Infrastructure_ebitda": 1281091.38,
      "Cloud Infrastructure_gross_margin": 59.49
    },
    {
      "month": "2024-08",
      "Enterprise Software_revenue": 8255398.37,
      "Enterprise Software_ebitda": 2383905.0,
      "Enterprise Software_gross_margin": 63.18,
      "Professional Services_revenue": 5379404.89,
      "Professional Services_ebitda": 1792774.77,
      "Professional Services_gross_margin": 53.72,
      "Cloud Infrastructure_revenue": 4440350.38,
      "Cloud Infrastructure_ebitda": 1341741.17,
      "Cloud Infrastructure_gross_margin": 62.11
    },
    {
      "month": "2024-09",
      "Enterprise Software_revenue": 8565928.81,
      "Enterprise Software_ebitda": 2916641.67,
      "Enterprise Software_gross_margin": 68.36,
      "Professional Services_revenue": 5446605.99,
      "Professional Services_ebitda": 1327623.4,
      "Professional Services_gross_margin": 48.16,
      "Cloud Infrastructure_revenue": 4696992.13,
      "Cloud Infrastructure_ebitda": 1255132.77,
      "Cloud Infrastructure_gross_margin": 58.79
    },
    {
      "month": "2024-10",
      "Enterprise Software_revenue": 9236218.26,
      "Enterprise Software_ebitda": 2673914.71,
      "Enterprise Software_gross_margin": 64.49,
      "Professional Services_revenue": 5626923.8,
      "Professional Services_ebitda": 1800212.27,
      "Professional Services_gross_margin": 49.93,
      "Cloud Infrastructure_revenue": 5099327.99,
      "Cloud Infrastructure_ebitda": 1477624.33,
      "Cloud Infrastructure_gross_margin": 59.49
    },
    {
      "month": "2024-11",
      "Enterprise Software_revenue": 9252268.73,
      "Enterprise Software_ebitda": 2799507.48,
      "Enterprise Software_gross_margin": 66.32,
      "Professional Services_revenue": 5559755.21,
      "Professional Services_ebitda": 1750305.39,
      "Professional Services_gross_margin": 53.4,
      "Cloud Infrastructure_revenue": 5273509.88,
      "Cloud Infrastructure_ebitda": 1837854.03,
      "Cloud Infrastructure_gross_margin": 63.74
    },
    {
      "month": "2024-12",
      "Enterprise Software_revenue": 9481364.27,
      "Enterprise Software_ebitda": 2791723.44,
      "Enterprise Software_gross_margin": 66.7,
      "Professional Services_revenue": 6101504.65,
      "Professional Services_ebitda": 1768973.18,
      "Professional Services_gross_margin": 50.31,
      "Cloud Infrastructure_revenue": 5392473.64,
      "Cloud Infrastructure_ebitda": 1643883.3,
      "Cloud Infrastructure_gross_margin": 61.28
    }
  ],
  "cashflow_waterfall": {
    "operating": 87097258.21,
    "investing": -39813663.81999999,
    "financing": -4766342.700000001,
    "net": 42517251.69
  },
  "working_capital": [
    {
      "month": "2023-01",
      "dso": 39.833333333333336,
      "dpo": 40.266666666666666,
      "dio": 5.433333333333334,
      "ccc": 5.133333333333333
    },
    {
      "month": "2023-02",
      "dso": 39.6,
      "dpo": 40.4,
      "dio": 6.033333333333334,
      "ccc": 5.233333333333333
    },
    {
      "month": "2023-03",
      "dso": 43.5,
      "dpo": 40.9,
      "dio": 5.8999999999999995,
      "ccc": 8.966666666666667
    },
    {
      "month": "2023-04",
      "dso": 43.06666666666666,
      "dpo": 40.23333333333333,
      "dio": 5.666666666666667,
      "ccc": 8.5
    },
    {
      "month": "2023-05",
      "dso": 43.06666666666666,
      "dpo": 38.833333333333336,
      "dio": 7.033333333333334,
      "ccc": 11.266666666666666
    },
    {
      "month": "2023-06",
      "dso": 44.06666666666666,
      "dpo": 39.86666666666667,
      "dio": 6.633333333333334,
      "ccc": 10.9
    },
    {
      "month": "2023-07",
      "dso": 45.4,
      "dpo": 41.46666666666667,
      "dio": 6.133333333333333,
      "ccc": 10.066666666666668
    },
    {
      "month": "2023-08",
      "dso": 44.833333333333336,
      "dpo": 41.36666666666667,
      "dio": 6.7,
      "ccc": 10.799999999999999
    },
    {
      "month": "2023-09",
      "dso": 43.1,
      "dpo": 39.666666666666664,
      "dio": 6.1000000000000005,
      "ccc": 11.533333333333331
    },
    {
      "month": "2023-10",
      "dso": 48.73333333333334,
      "dpo": 39.766666666666666,
      "dio": 4.633333333333333,
      "ccc": 13.6
    },
    {
      "month": "2023-11",
      "dso": 50.166666666666664,
      "dpo": 42.4,
      "dio": 5.8999999999999995,
      "ccc": 13.666666666666666
    },
    {
      "month": "2023-12",
      "dso": 47.633333333333326,
      "dpo": 40.03333333333333,
      "dio": 5.5,
      "ccc": 13.1
    },
    {
      "month": "2024-01",
      "dso": 57.93333333333334,
      "dpo": 40.06666666666667,
      "dio": 5.433333333333334,
      "ccc": 23.3
    },
    {
      "month": "2024-02",
      "dso": 39.233333333333334,
      "dpo": 39.6,
      "dio": 7.433333333333334,
      "ccc": 7.066666666666667
    },
    {
      "month": "2024-03",
      "dso": 42.3,
      "dpo": 42.56666666666667,
      "dio": 7.866666666666667,
      "ccc": 7.6000000000000005
    },
    {
      "month": "2024-04",
      "dso": 42.4,
      "dpo": 41.333333333333336,
      "dio": 7.366666666666666,
      "ccc": 8.433333333333334
    },
    {
      "month": "2024-05",
      "dso": 43.6,
      "dpo": 41.233333333333334,
      "dio": 7.266666666666667,
      "ccc": 9.299999999999999
    },
    {
      "month": "2024-06",
      "dso": 45.300000000000004,
      "dpo": 39.03333333333333,
      "dio": 6.3,
      "ccc": 11.966666666666667
    },
    {
      "month": "2024-07",
      "dso": 45.46666666666667,
      "dpo": 40.6,
      "dio": 6.400000000000001,
      "ccc": 11.266666666666667
    },
    {
      "month": "2024-08",
      "dso": 46.76666666666667,
      "dpo": 40.166666666666664,
      "dio": 6.766666666666667,
      "ccc": 12.833333333333334
    },
    {
      "month": "2024-09",
      "dso": 45.06666666666666,
      "dpo": 40.53333333333333,
      "dio": 5.800000000000001,
      "ccc": 10.333333333333334
    },
    {
      "month": "2024-10",
      "dso": 50.4,
      "dpo": 41.4,
      "dio": 5.266666666666667,
      "ccc": 14.266666666666666
    },
    {
      "month": "2024-11",
      "dso": 50.46666666666667,
      "dpo": 41.266666666666666,
      "dio": 7.199999999999999,
      "ccc": 16.400000000000002
    },
    {
      "month": "2024-12",
      "dso": 47.900000000000006,
      "dpo": 40.53333333333333,
      "dio": 6.7,
      "ccc": 14.066666666666668
    }
  ],
  "validation_report": {
    "rows_loaded": 219,
    "nulls_found": 125,
    "duplicates_removed": 3,
    "division_variants_normalized": 11
  },
  "raw_sample": [
    {
      "date": "2023-05-31",
      "division": "Div A",
      "revenue": 7335585.69,
      "cogs": 2345926.08,
      "gross_profit": 4989659.61,
      "gross_margin_pct": 68.02,
      "rd_expense": 1163104.69,
      "sga_expense": 1365756.29,
      "total_opex": 2528860.98,
      "ebitda": 2460798.63,
      "ebitda_margin_pct": 33.55,
      "depreciation": 220783.9,
      "ebit": 2240014.73,
      "interest_expense": 75506.0,
      "pretax_income": 2164508.73
    },
    {
      "date": "2024-04-30",
      "division": "Cloud Infrastructure",
      "revenue": 4946785.73,
      "cogs": 2035559.0,
      "gross_profit": 2911226.73,
      "gross_margin_pct": 58.85,
      "rd_expense": 704470.21,
      "sga_expense": 751046.95,
      "total_opex": 1455517.16,
      "ebitda": 1455709.57,
      "ebitda_margin_pct": 29.43,
      "depreciation": 300758.15,
      "ebit": 1154951.42,
      "interest_expense": 62582.64,
      "pretax_income": 1092368.78
    },
    {
      "date": "2024-07-31",
      "division": "Enterprise Software",
      "revenue": 8552031.64,
      "cogs": 3026506.82,
      "gross_profit": 5525524.82,
      "gross_margin_pct": 64.61,
      "rd_expense": 1418249.61,
      "sga_expense": 1611159.86,
      "total_opex": 3029409.47,
      "ebitda": 2496115.35,
      "ebitda_margin_pct": 29.19,
      "depreciation": null,
      "ebit": 2234084.62,
      "interest_expense": 86191.86,
      "pretax_income": 2147892.76
    },
    {
      "date": "2023-01-31",
      "division": "Enterprise Software",
      "revenue": 6314697.25,
      "cogs": 2129061.09,
      "gross_profit": 4185636.16,
      "gross_margin_pct": 66.28,
      "rd_expense": 1121976.54,
      "sga_expense": 1191589.68,
      "total_opex": 2313566.22,
      "ebitda": 1872069.94,
      "ebitda_margin_pct": 29.65,
      "depreciation": 186257.72,
      "ebit": 1685812.22,
      "interest_expense": 60543.8,
      "pretax_income": 1625268.42
    },
    {
      "date": "2023-05-31",
      "division": "Div B",
      "revenue": 4913430.85,
      "cogs": 2458759.37,
      "gross_profit": 2454671.48,
      "gross_margin_pct": 49.96,
      "rd_expense": 189643.8,
      "sga_expense": 830559.09,
      "total_opex": 1020202.89,
      "ebitda": 1434468.59,
      "ebitda_margin_pct": 29.19,
      "depreciation": 94814.03,
      "ebit": 1339654.56,
      "interest_expense": 36424.16,
      "pretax_income": 1303230.4
    }
  ],
  "clean_sample": [
    {
      "date": "2023-01-31",
      "division": "Cloud Infrastructure",
      "revenue": 3641344.72,
      "cogs": 1383412.42,
      "gross_profit": 2257932.3,
      "gross_margin_pct": 62.01,
      "rd_expense": 512607.22,
      "sga_expense": 609187.06,
      "total_opex": 1121794.28,
      "ebitda": 1136138.02,
      "ebitda_margin_pct": 31.2,
      "depreciation": 219482.25,
      "ebit": 916655.77,
      "interest_expense": 44854.23,
      "pretax_income": 871801.54
    },
    {
      "date": "2023-01-31",
      "division": "Enterprise Software",
      "revenue": 6314697.25,
      "cogs": 2129061.09,
      "gross_profit": 4185636.16,
      "gross_margin_pct": 66.28,
      "rd_expense": 1121976.54,
      "sga_expense": 1191589.68,
      "total_opex": 2313566.22,
      "ebitda": 1872069.94,
      "ebitda_margin_pct": 29.65,
      "depreciation": 186257.72,
      "ebit": 1685812.22,
      "interest_expense": 60543.8,
      "pretax_income": 1625268.42
    },
    {
      "date": "2023-01-31",
      "division": "Professional Services",
      "revenue": 4392843.16,
      "cogs": 2210650.19,
      "gross_profit": 2182192.97,
      "gross_margin_pct": 57.25,
      "rd_expense": 182761.66,
      "sga_expense": 770894.68,
      "total_opex": 953656.34,
      "ebitda": 1228536.63,
      "ebitda_margin_pct": 27.97,
      "depreciation": 90206.86,
      "ebit": 1138329.77,
      "interest_expense": 47303.0,
      "pretax_income": 1103458.51
    },
    {
      "date": "2023-02-28",
      "division": "Cloud Infrastructure",
      "revenue": 3721488.05,
      "cogs": 1495751.09,
      "gross_profit": 2225736.96,
      "gross_margin_pct": 59.81,
      "rd_expense": 525109.21,
      "sga_expense": 669079.43,
      "total_opex": 1149861.73,
      "ebitda": 1075875.23,
      "ebitda_margin_pct": 28.91,
      "depreciation": 221530.92,
      "ebit": 854344.31,
      "interest_expense": 45821.57,
      "pretax_income": 808522.74
    },
    {
      "date": "2023-02-28",
      "division": "Enterprise Software",
      "revenue": 6636557.69,
      "cogs": 2198954.26,
      "gross_profit": 4437603.43,
      "gross_margin_pct": 66.87,
      "rd_expense": 1152726.59,
      "sga_expense": 1210595.65,
      "total_opex": 2363322.24,
      "ebitda": 2074281.19,
      "ebitda_margin_pct": 31.26,
      "depreciation": 246728.43,
      "ebit": 1874260.01,
      "interest_expense": 66752.77,
      "pretax_income": 1807507.24
    }
  ]
}
